import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';
import { permisoGuard } from './core/guards/permiso.guard';
import { AJUSTES_INVENTARIO_ROUTES } from './features/inventario/ajustes.routes';
import { FACTURAS_PROVEEDOR_ROUTES } from './features/compras/facturas-proveedor/facturas-proveedor.routes';
import { PEDIDOS_VENTA_ROUTES } from './features/pedidos-venta/pedidos-venta.routes';

export const routes: Routes = [
  { path: '', redirectTo: 'login', pathMatch: 'full' },
  { path: 'varistorehn/productos', data: { preloadAfterRender: true }, loadComponent: () => import('./features/varistorehn/varistorehn-productos.component').then(m => m.VaristorehnProductosComponent) },
  { path: 'varistorehn/ofertas', data: { soloOfertas: true }, loadComponent: () => import('./features/varistorehn/varistorehn-productos.component').then(m => m.VaristorehnProductosComponent) },
  { path: 'varistorehn/producto/:slug', data: { preloadAfterRender: true }, loadComponent: () => import('./features/varistorehn/varistorehn-producto.component').then(m => m.VaristorehnProductoComponent) },
  { path: 'varistorehn/categorias', data: { preloadAfterRender: true }, loadComponent: () => import('./features/varistorehn/varistorehn-categorias.component').then(m => m.VaristorehnCategoriasComponent) },
  { path: 'varistorehn/categoria/:slug', loadComponent: () => import('./features/varistorehn/varistorehn-categoria.component').then(m => m.VaristorehnCategoriaComponent) },
  { path: 'varistorehn/carrito', loadComponent: () => import('./features/varistorehn/varistorehn-carrito.component').then(m => m.VaristorehnCarritoComponent) },
  { path: 'varistorehn/checkout', loadComponent: () => import('./features/varistorehn/varistorehn-checkout.component').then(m => m.VaristorehnCheckoutComponent) },
  { path: 'varistorehn/cuenta', loadComponent: () => import('./features/varistorehn/varistorehn-cuenta.component').then(m => m.VaristorehnCuentaComponent) },
  { path: 'varistorehn/pedido/:id', loadComponent: () => import('./features/varistorehn/varistorehn-pedido.component').then(m => m.VaristorehnPedidoComponent) },
  { path: 'varistorehn', loadComponent: () => import('./features/varistorehn/varistorehn.component').then(m => m.VaristorehnComponent) },
  { path: 'login', loadComponent: () => import('./features/login/login.component').then(m => m.LoginComponent) },
  { path: 'dashboard', canActivate: [authGuard, permisoGuard], data: { modulo: 'Dashboard', accion: 'Ver' }, loadComponent: () => import('./features/dashboard/dashboard.component').then(m => m.DashboardComponent) },
  { path: 'productos', canActivate: [authGuard, permisoGuard], data: { modulo: 'Productos', accion: 'Ver' }, loadComponent: () => import('./features/productos/productos-list.component').then(m => m.ProductosListComponent) },
  { path: 'productos/nuevo', canActivate: [authGuard, permisoGuard], data: { modulo: 'Productos', accion: 'Crear' }, loadComponent: () => import('./features/productos/producto-form.component').then(m => m.ProductoFormComponent) },
  { path: 'productos/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Productos', accion: 'Editar' }, loadComponent: () => import('./features/productos/producto-form.component').then(m => m.ProductoFormComponent) },
  { path: 'productos/:id/variantes', canActivate: [authGuard, permisoGuard], data: { modulo: 'Productos', accion: 'Editar' }, loadComponent: () => import('./features/productos/producto-variantes.component').then(m => m.ProductoVariantesComponent) },
  { path: 'productos/:id', canActivate: [authGuard, permisoGuard], data: { modulo: 'Productos', accion: 'Ver' }, loadComponent: () => import('./features/productos/producto-detail.component').then(m => m.ProductoDetailComponent) },
  { path: 'categorias', canActivate: [authGuard, permisoGuard], data: { modulo: 'Categorias', accion: 'Ver' }, loadComponent: () => import('./features/categorias/categorias-list.component').then(m => m.CategoriasListComponent) },
  { path: 'categorias/nueva', canActivate: [authGuard, permisoGuard], data: { modulo: 'Categorias', accion: 'Crear' }, loadComponent: () => import('./features/categorias/categoria-form.component').then(m => m.CategoriaFormComponent) },
  { path: 'categorias/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Categorias', accion: 'Editar' }, loadComponent: () => import('./features/categorias/categoria-form.component').then(m => m.CategoriaFormComponent) },
  { path: 'sucursales', canActivate: [authGuard, permisoGuard], data: { modulo: 'Sucursales', accion: 'Ver' }, loadComponent: () => import('./features/sucursales/sucursales-list.component').then(m => m.SucursalesListComponent) },
  { path: 'sucursales/nueva', canActivate: [authGuard, permisoGuard], data: { modulo: 'Sucursales', accion: 'Crear' }, loadComponent: () => import('./features/sucursales/sucursal-form.component').then(m => m.SucursalFormComponent) },
  { path: 'sucursales/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Sucursales', accion: 'Editar' }, loadComponent: () => import('./features/sucursales/sucursal-form.component').then(m => m.SucursalFormComponent) },
  { path: 'colores', canActivate: [authGuard, permisoGuard], data: { modulo: 'Colores', accion: 'Ver', tipo: 'Color', titulo: 'Colores', singular: 'Color', icono: 'palette' }, loadComponent: () => import('./features/catalogos-producto/catalogo-producto-list.component').then(m => m.CatalogoProductoListComponent) },
  { path: 'tallas', canActivate: [authGuard, permisoGuard], data: { modulo: 'Tallas', accion: 'Ver', tipo: 'Talla', titulo: 'Tallas', singular: 'Talla', icono: 'straighten' }, loadComponent: () => import('./features/catalogos-producto/catalogo-producto-list.component').then(m => m.CatalogoProductoListComponent) },
  { path: 'marcas', canActivate: [authGuard, permisoGuard], data: { modulo: 'Marcas', accion: 'Ver', tipo: 'Marca', titulo: 'Marcas', singular: 'Marca', icono: 'branding_watermark' }, loadComponent: () => import('./features/catalogos-producto/catalogo-producto-list.component').then(m => m.CatalogoProductoListComponent) },
  { path: 'modelos', canActivate: [authGuard, permisoGuard], data: { modulo: 'Modelos', accion: 'Ver', tipo: 'Modelo', titulo: 'Modelos', singular: 'Modelo', icono: 'devices' }, loadComponent: () => import('./features/catalogos-producto/catalogo-producto-list.component').then(m => m.CatalogoProductoListComponent) },
  { path: 'metodos-pago', canActivate: [authGuard, permisoGuard], data: { modulo: 'MetodosPago', accion: 'Ver' }, loadComponent: () => import('./features/metodos-pago/metodos-pago.component').then(m => m.MetodosPagoComponent) },
  { path: 'proveedores', canActivate: [authGuard, permisoGuard], data: { modulo: 'Proveedores', accion: 'Ver' }, loadComponent: () => import('./features/proveedores/proveedores-list.component').then(m => m.ProveedoresListComponent) },
  { path: 'proveedores/nuevo', canActivate: [authGuard, permisoGuard], data: { modulo: 'Proveedores', accion: 'Crear' }, loadComponent: () => import('./features/proveedores/proveedor-form.component').then(m => m.ProveedorFormComponent) },
  { path: 'proveedores/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Proveedores', accion: 'Editar' }, loadComponent: () => import('./features/proveedores/proveedor-form.component').then(m => m.ProveedorFormComponent) },
  { path: 'clientes', canActivate: [authGuard, permisoGuard], data: { modulo: 'Clientes', accion: 'Ver' }, loadComponent: () => import('./features/clientes/clientes-list.component').then(m => m.ClientesListComponent) },
  { path: 'clientes/nuevo', canActivate: [authGuard, permisoGuard], data: { modulo: 'Clientes', accion: 'Crear' }, loadComponent: () => import('./features/clientes/cliente-form.component').then(m => m.ClienteFormComponent) },
  { path: 'clientes/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Clientes', accion: 'Editar' }, loadComponent: () => import('./features/clientes/cliente-form.component').then(m => m.ClienteFormComponent) },
  { path: 'tipo-clientes', canActivate: [authGuard, permisoGuard], data: { modulo: 'TiposClientes', accion: 'Ver' }, loadComponent: () => import('./features/tipo-clientes/tipo-clientes-list.component').then(m => m.TiposClientesListComponent) },
  { path: 'tipo-clientes/nuevo', canActivate: [authGuard, permisoGuard], data: { modulo: 'TiposClientes', accion: 'Crear' }, loadComponent: () => import('./features/tipo-clientes/tipo-cliente-form.component').then(m => m.TipoClienteFormComponent) },
  { path: 'tipo-clientes/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'TiposClientes', accion: 'Editar' }, loadComponent: () => import('./features/tipo-clientes/tipo-cliente-form.component').then(m => m.TipoClienteFormComponent) },
  { path: 'usuarios', canActivate: [authGuard, permisoGuard], data: { modulo: 'Usuarios', accion: 'Ver' }, loadComponent: () => import('./features/usuarios/usuarios.component').then(m => m.UsuariosComponent) },
  { path: 'usuarios/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Usuarios', accion: 'Editar' }, loadComponent: () => import('./features/usuarios/usuario-form.component').then(m => m.UsuarioFormComponent) },
  { path: 'usuarios/:id', canActivate: [authGuard, permisoGuard], data: { modulo: 'Usuarios', accion: 'Ver' }, loadComponent: () => import('./features/usuarios/usuario-detail.component').then(m => m.UsuarioDetailComponent) },
  { path: 'roles', canActivate: [authGuard, permisoGuard], data: { modulo: 'Roles', accion: 'Ver' }, loadComponent: () => import('./features/roles/roles-list.component').then(m => m.RolesListComponent) },
  { path: 'roles/nuevo', canActivate: [authGuard, permisoGuard], data: { modulo: 'Roles', accion: 'Crear' }, loadComponent: () => import('./features/roles/rol-form.component').then(m => m.RolFormComponent) },
  { path: 'roles/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Roles', accion: 'Editar' }, loadComponent: () => import('./features/roles/rol-form.component').then(m => m.RolFormComponent) },
  { path: 'permisos', canActivate: [authGuard, permisoGuard], data: { modulo: 'Permisos', accion: 'Administrar' }, loadComponent: () => import('./features/permisos/permisos-matrix.component').then(m => m.PermisosMatrixComponent) },
  { path: 'descuentos', canActivate: [authGuard, permisoGuard], data: { modulo: 'Descuentos', accion: 'Ver' }, loadComponent: () => import('./features/descuentos/descuentos-list.component').then(m => m.DescuentosListComponent) },
  { path: 'descuentos/nuevo', canActivate: [authGuard, permisoGuard], data: { modulo: 'Descuentos', accion: 'Crear' }, loadComponent: () => import('./features/descuentos/descuento-form.component').then(m => m.DescuentoFormComponent) },
  { path: 'descuentos/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Descuentos', accion: 'Editar' }, loadComponent: () => import('./features/descuentos/descuento-form.component').then(m => m.DescuentoFormComponent) },
  { path: 'impuestos', canActivate: [authGuard, permisoGuard], data: { modulo: 'Impuestos', accion: 'Ver' }, loadComponent: () => import('./features/impuestos/impuestos-list.component').then(m => m.ImpuestosListComponent) },
  { path: 'impuestos/nuevo', canActivate: [authGuard, permisoGuard], data: { modulo: 'Impuestos', accion: 'Crear' }, loadComponent: () => import('./features/impuestos/impuesto-form.component').then(m => m.ImpuestoFormComponent) },
  { path: 'impuestos/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Impuestos', accion: 'Editar' }, loadComponent: () => import('./features/impuestos/impuesto-form.component').then(m => m.ImpuestoFormComponent) },
  { path: 'costos-envio', canActivate: [authGuard, permisoGuard], data: { modulo: 'Facturacion', accion: 'Administrar' }, loadComponent: () => import('./features/costos-envio/costos-envio.component').then(m => m.CostosEnvioComponent) },
  { path: 'cargas-masivas', canActivate: [authGuard, permisoGuard], data: { modulo: 'CargasMasivas', accion: 'Ver' }, loadComponent: () => import('./features/cargas-masivas/cargas-masivas.component').then(m => m.CargasMasivasComponent) },
  { path: 'auditoria', canActivate: [authGuard, permisoGuard], data: { modulo: 'Auditoria', accion: 'Ver' }, loadComponent: () => import('./features/auditoria/auditoria-list.component').then(m => m.AuditoriaListComponent) },
  { path: 'solicitudes-compra', canActivate: [authGuard, permisoGuard], data: { modulo: 'Compras', accion: 'Ver' }, loadComponent: () => import('./features/solicitudes-compra/solicitudes-compra-shell.component').then(m => m.SolicitudesCompraShellComponent) },
  { path: 'ordenes-compra', canActivate: [authGuard, permisoGuard], data: { modulo: 'Compras', accion: 'Ver' }, loadComponent: () => import('./features/ordenes-compra/ordenes-compra-shell.component').then(m => m.OrdenesCompraShellComponent) },
  { path: 'ordenes-compra/nueva', canActivate: [authGuard, permisoGuard], data: { modulo: 'Compras', accion: 'Crear' }, loadComponent: () => import('./features/ordenes-compra/orden-compra-form.component').then(m => m.OrdenCompraFormComponent) },
  { path: 'ordenes-compra/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Compras', accion: 'Editar' }, loadComponent: () => import('./features/ordenes-compra/orden-compra-form.component').then(m => m.OrdenCompraFormComponent) },
  { path: 'compras', canActivate: [authGuard, permisoGuard], data: { modulo: 'Compras', accion: 'Ver' }, loadComponent: () => import('./features/compras/compras-list.component').then(m => m.ComprasListComponent) },
  { path: 'compras/nueva', canActivate: [authGuard, permisoGuard], data: { modulo: 'Compras', accion: 'Crear' }, loadComponent: () => import('./features/compras/compra-form.component').then(m => m.CompraFormComponent) },
  { path: 'compras/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Compras', accion: 'Editar' }, loadComponent: () => import('./features/compras/compra-form.component').then(m => m.CompraFormComponent) },
  { path: 'compras/:id', canActivate: [authGuard, permisoGuard], data: { modulo: 'Compras', accion: 'Ver' }, loadComponent: () => import('./features/compras/compra-detail.component').then(m => m.CompraDetailComponent) },
  { path: 'ventas', canActivate: [authGuard, permisoGuard], data: { modulo: 'Ventas', accion: 'Ver' }, loadComponent: () => import('./features/ventas/ventas-list.component').then(m => m.VentasListComponent) },
  { path: 'ventas/nueva', canActivate: [authGuard, permisoGuard], data: { modulo: 'Ventas', accion: 'Crear' }, loadComponent: () => import('./features/ventas/venta-form.component').then(m => m.VentaFormComponent) },
  { path: 'ventas/:id/editar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Ventas', accion: 'Editar' }, loadComponent: () => import('./features/ventas/venta-form.component').then(m => m.VentaFormComponent) },
  { path: 'ventas/:id', canActivate: [authGuard, permisoGuard], data: { modulo: 'Ventas', accion: 'Ver' }, loadComponent: () => import('./features/ventas/venta-detail.component').then(m => m.VentaDetailComponent) },
  { path: 'facturas/:id/pagos', canActivate: [authGuard, permisoGuard], data: { modulo: 'Facturacion', accion: 'Aplicar' }, loadComponent: () => import('./features/facturas/factura-pagos.component').then(m => m.FacturaPagosComponent) },
  { path: 'facturas/:id', canActivate: [authGuard, permisoGuard], data: { modulo: 'Facturacion', accion: 'Ver' }, loadComponent: () => import('./features/facturas/factura-view.component').then(m => m.FacturaViewComponent) },
  { path: 'cuentas-por-cobrar', canActivate: [authGuard, permisoGuard], data: { modulo: 'Facturacion', accion: 'Ver' }, loadComponent: () => import('./features/cuentas-por-cobrar/cuentas-por-cobrar.component').then(m => m.CuentasPorCobrarComponent) },
  { path: 'asientos-contables', canActivate: [authGuard, permisoGuard], data: { modulo: 'Finanzas', accion: 'Ver' }, loadComponent: () => import('./features/asientos-contables/asientos-contables.component').then(m => m.AsientosContablesComponent) },
  { path: 'finanzas', canActivate: [authGuard, permisoGuard], data: { modulo: 'Finanzas', accion: 'Ver' }, loadComponent: () => import('./features/finanzas/finanzas.component').then(m => m.FinanzasComponent) },
  { path: 'estados-financieros', canActivate: [authGuard, permisoGuard], data: { modulo: 'Finanzas', accion: 'Ver' }, loadComponent: () => import('./features/estados-financieros/estados-financieros.component').then(m => m.EstadosFinancierosComponent) },
  {
    path: 'centro-reportes', canActivate: [authGuard],
    loadComponent: () => import('./features/centro-reportes/centro-reportes.component').then(m => m.CentroReportesComponent),
    children: [
      { path: 'financieros', canActivate: [permisoGuard], data: { modulo: 'Finanzas', accion: 'Ver' }, loadComponent: () => import('./features/estados-financieros/estados-financieros.component').then(m => m.EstadosFinancierosComponent) },
      { path: 'administrativos', canActivate: [permisoGuard], data: { modulo: 'ReportesAdministrativos', accion: 'Ver' }, loadComponent: () => import('./features/reportes-administrativos/reportes-administrativos.component').then(m => m.ReportesAdministrativosComponent) },
      { path: 'inventario/valorizacion', canActivate: [permisoGuard], data: { modulo: 'Inventario', accion: 'Ver' }, loadComponent: () => import('./features/reportes-inventario/valorizacion/valorizacion.component').then(m => m.ValorizacionComponent) },
      { path: 'inventario/kardex', canActivate: [permisoGuard], data: { modulo: 'MovimientosInventario', accion: 'ConsultarHistorial' }, loadComponent: () => import('./features/reportes-inventario/kardex/kardex.component').then(m => m.KardexComponent) },
      { path: 'inventario/stock-health', canActivate: [permisoGuard], data: { modulo: 'Inventario', accion: 'Ver' }, loadComponent: () => import('./features/reportes-inventario/stock-health/stock-health.component').then(m => m.StockHealthComponent) },
      { path: 'inventario/reconciliacion', canActivate: [permisoGuard], data: { modulo: 'Inventario', accion: 'Ver' }, loadComponent: () => import('./features/reportes-inventario/reconciliacion/reconciliacion.component').then(m => m.ReconciliacionComponent) },
      { path: 'ventas', canActivate: [permisoGuard], data: { modulo: 'Ventas', accion: 'Ver' }, loadComponent: () => import('./features/reportes-ventas/reportes-ventas.component').then(m => m.ReportesVentasComponent) },
      { path: 'compras', canActivate: [permisoGuard], data: { modulo: 'Compras', accion: 'Ver' }, loadComponent: () => import('./features/reportes-compras/reportes-compras.component').then(m => m.ReportesComprasComponent) },
      { path: 'rentabilidad', canActivate: [permisoGuard], data: { modulo: 'Ventas', accion: 'Ver' }, loadComponent: () => import('./features/rentabilidad/rentabilidad.component').then(m => m.RentabilidadComponent) }
    ]
  },
  { path: 'plan-cuentas', canActivate: [authGuard, permisoGuard], data: { modulo: 'Finanzas', accion: 'Ver' }, loadComponent: () => import('./features/plan-cuentas/plan-cuentas.component').then(m => m.PlanCuentasComponent) },
  { path: 'cuentas-bancarias', canActivate: [authGuard, permisoGuard], data: { modulo: 'Finanzas', accion: 'Ver' }, loadComponent: () => import('./features/cuentas-bancarias/cuentas-bancarias.component').then(m => m.CuentasBancariasComponent) },
  { path: 'inventario/movimientos', canActivate: [authGuard, permisoGuard], data: { modulo: 'MovimientosInventario', accion: 'Ver' }, loadComponent: () => import('./features/inventario/movimientos-list.component').then(m => m.MovimientosListComponent) },
  { path: 'inventario/costeo', canActivate: [authGuard, permisoGuard], data: { modulo: 'MovimientosInventario', accion: 'Ver' }, loadComponent: () => import('./features/inventario/costeo-inventario.component').then(m => m.CosteoInventarioComponent) },
  ...AJUSTES_INVENTARIO_ROUTES,
  ...FACTURAS_PROVEEDOR_ROUTES,
  ...PEDIDOS_VENTA_ROUTES,
  { path: 'configuracion', canActivate: [authGuard, permisoGuard], data: { modulo: 'Configuracion', accion: 'Ver' }, loadComponent: () => import('./features/configuracion/configuracion.component').then(m => m.ConfiguracionComponent) },
  { path: 'periodos-contables', canActivate: [authGuard, permisoGuard], data: { modulo: 'Configuracion', accion: 'Ver' }, loadComponent: () => import('./features/periodos-contables/periodos-contables.component').then(m => m.PeriodosContablesComponent) },
  { path: 'perfil', canActivate: [authGuard], loadComponent: () => import('./features/perfil/perfil.component').then(m => m.PerfilComponent) },
  { path: '**', redirectTo: '' }
];