import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal, ChangeDetectionStrategy } from '@angular/core';
import { FormArray, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { PermisosRuntimeService } from '../../core/auth/permisos-runtime.service';
import { Cliente } from '../../core/models/cliente.model';
import { Producto } from '../../core/models/producto.model';
import { ClienteService } from '../../services/cliente.service';
import { ProductoService } from '../../services/producto.service';
import { Cotizacion, CotizacionDetalleInput, EstadoCotizacion } from './cotizacion.model';
import { CotizacionService } from './cotizacion.service';
import { AppAlertService } from '../../shared/alerts/app-alert.service';
const UI=[CommonModule,RouterLink,MatButtonModule,MatCardModule,MatFormFieldModule,MatIconModule,MatInputModule,MatSelectModule,MatSnackBarModule,MatProgressSpinnerModule];
const estado=(e:EstadoCotizacion)=>EstadoCotizacion[e]??String(e);
@Component({selector:'app-cotizaciones-list',standalone:true,imports:UI,template:`<section class="page"><header><div><h1>Cotizaciones</h1><p>Gestión comercial de cotizaciones.</p></div>@if(puede('Crear')){<a mat-flat-button color="primary" routerLink="/cotizaciones/nueva"><mat-icon>add</mat-icon>Nueva</a>}</header><mat-card><mat-card-content><div class="filters"><mat-form-field appearance="outline"><mat-label>Estado</mat-label><mat-select [value]="filtroEstado" (selectionChange)="filtrar($event.value)"><mat-option [value]="null">Todos</mat-option>@for(e of estados;track e){<mat-option [value]="e">{{nombre(e)}}</mat-option>}</mat-select></mat-form-field></div>@if(loading()){<div class="center"><mat-spinner diameter="40"/></div>}@else if(error()){<div class="center">No fue posible cargar las cotizaciones. <button mat-button (click)="cargar()">Reintentar</button></div>}@else{<div class="table"><table><thead><tr><th>ID</th><th>Cliente</th><th>Creada</th><th>Estado</th><th>Total</th><th></th></tr></thead><tbody>@for(c of items();track c.id){<tr><td>COT-{{c.id}}</td><td>{{c.clienteNombreSnapshot}}</td><td>{{c.createdAt|date:'dd/MM/yyyy'}}</td><td>{{nombre(c.estado)}}</td><td>{{c.total|number:'1.2-2'}}</td><td><a mat-icon-button [routerLink]="['/cotizaciones',c.id]" aria-label="Ver cotización"><mat-icon>visibility</mat-icon></a>@if(c.estado===EstadoCotizacion.Borrador&&puede('Editar')){<a mat-icon-button [routerLink]="['/cotizaciones',c.id,'editar']" aria-label="Editar cotización"><mat-icon>edit</mat-icon></a>}</td></tr>}@empty{<tr><td colspan="6">Sin resultados.</td></tr>}</tbody></table></div><footer><span>{{total()}} registro(s)</span><div><button mat-button [disabled]="page<=1" (click)="pagina(page-1)">Anterior</button><span>Página {{page}}</span><button mat-button [disabled]="page*pageSize>=total()" (click)="pagina(page+1)">Siguiente</button></div></footer>}</mat-card-content></mat-card></section>`,changeDetection: ChangeDetectionStrategy.Eager,
styles:[`.page{max-width:1200px;margin:auto;padding:16px}header,footer{display:flex;justify-content:space-between;gap:16px;align-items:center}header{margin-bottom:16px}h1{margin:0}.filters{max-width:280px}.center{text-align:center;padding:36px}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;text-align:left;border-bottom:1px solid var(--color-border)}footer{padding-top:12px}footer div{display:flex;gap:8px;align-items:center}@media(max-width:700px){header,footer{align-items:flex-start;flex-direction:column}}`]})
export class CotizacionesListComponent implements OnInit{private svc=inject(CotizacionService);private permisos=inject(PermisosRuntimeService);readonly items=signal<Cotizacion[]>([]);readonly total=signal(0);readonly loading=signal(false);readonly error=signal(false);readonly EstadoCotizacion=EstadoCotizacion;readonly estados=[1,2,3,4,5] as EstadoCotizacion[];page=1;pageSize=10;filtroEstado:EstadoCotizacion|null=null;ngOnInit(){this.cargar()}puede(a:string){return this.permisos.puede('Ventas',a)}nombre(e:EstadoCotizacion){return estado(e)}filtrar(e:EstadoCotizacion|null){this.filtroEstado=e;this.page=1;this.cargar()}pagina(p:number){this.page=Math.max(1,p);this.cargar()}cargar(){this.loading.set(true);this.error.set(false);this.svc.getPaged({page:this.page,pageSize:this.pageSize,estado:this.filtroEstado,sortBy:'CreatedAt',sortDirection:'desc'}).subscribe({next:r=>{this.items.set(r.data.items);this.total.set(r.data.totalCount);this.loading.set(false)},error:()=>{this.error.set(true);this.loading.set(false)}})}}
@Component({selector:'app-cotizacion-form',standalone:true,imports:[...UI,ReactiveFormsModule],template:`<section class="page"><header><h1>{{editando?'Editar':'Nueva'}} cotización</h1><a mat-stroked-button routerLink="/cotizaciones">Cancelar</a></header>@if(loading()){<div class="center"><mat-spinner diameter="40"/></div>}@else{<form [formGroup]="form" (ngSubmit)="guardar()"><mat-card><mat-card-content class="grid"><mat-form-field appearance="outline"><mat-label>Cliente</mat-label><mat-select formControlName="clienteId">@for(c of clientes();track c.id){<mat-option [value]="c.id">{{c.nombre}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>Observaciones</mat-label><textarea matInput formControlName="observaciones"></textarea></mat-form-field></mat-card-content></mat-card><mat-card><mat-card-content><div class="row"><h2>Detalles</h2><button mat-stroked-button type="button" (click)="agregar()">Agregar</button></div><div formArrayName="detalles">@for(g of detalles.controls;track $index;let i=$index){<div class="detail" [formGroupName]="i"><mat-form-field appearance="outline"><mat-label>Producto</mat-label><mat-select formControlName="productoId" (selectionChange)="producto(i,$event.value)">@for(p of productos();track p.id){<mat-option [value]="p.id">{{p.nombre}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>Cantidad</mat-label><input matInput type="number" min="0.0001" step="0.0001" formControlName="cantidad"></mat-form-field><mat-form-field appearance="outline"><mat-label>Precio (catálogo)</mat-label><input matInput type="number" formControlName="precioUnitario" readonly aria-readonly="true"></mat-form-field><button mat-icon-button type="button" (click)="quitar(i)" aria-label="Quitar detalle"><mat-icon>delete</mat-icon></button></div>}</div>@if(!detalles.length){<p>Agregue al menos un producto.</p>}</mat-card-content></mat-card><div class="actions"><button mat-flat-button color="primary" type="submit" [disabled]="saving()">Guardar</button></div></form>}</section>`,changeDetection: ChangeDetectionStrategy.Eager,
styles:[`.page{max-width:1100px;margin:auto;padding:16px}header,.row,.actions{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.detail{display:grid;grid-template-columns:2fr 1fr 1fr 48px;gap:8px}mat-card{margin-bottom:16px}.center{text-align:center;padding:36px}@media(max-width:760px){.grid,.detail{grid-template-columns:1fr}}`]})
export class CotizacionFormComponent implements OnInit{private fb=inject(FormBuilder);private svc=inject(CotizacionService);private cs=inject(ClienteService);private ps=inject(ProductoService);private route=inject(ActivatedRoute);private router=inject(Router);private snack=inject(MatSnackBar);readonly clientes=signal<Cliente[]>([]);readonly productos=signal<Producto[]>([]);readonly loading=signal(false);readonly saving=signal(false);editando=false;id?:number;readonly form=this.fb.group({clienteId:[null as number|null,Validators.required],observaciones:[''],detalles:this.fb.array([])});get detalles(){return this.form.controls.detalles as FormArray}ngOnInit(){this.cs.getActivos().subscribe({next:r=>this.clientes.set(r.data)});this.ps.getPaged({page:1,pageSize:100,activo:true}).subscribe({next:r=>this.productos.set(r.data.items)});const id=Number(this.route.snapshot.paramMap.get('id'));if(Number.isInteger(id)&&id>0){this.editando=true;this.id=id;this.cargar(id)}else this.agregar()}grupo(d?:Partial<CotizacionDetalleInput>){return this.fb.group({id:[d?.id??null],productoId:[d?.productoId??null as number|null,Validators.required],productoVarianteId:[d?.productoVarianteId??null],cantidad:[d?.cantidad??1,[Validators.required,Validators.min(.0001)]],precioUnitario:[d?.precioUnitario??0,[Validators.required,Validators.min(0)]]})}agregar(){this.detalles.push(this.grupo())}quitar(i:number){this.detalles.removeAt(i)}producto(i:number,id:number){const p=this.productos().find(x=>x.id===id);if(p)this.detalles.at(i).patchValue({precioUnitario:p.precio??0})}private cargar(id:number){this.loading.set(true);this.svc.getById(id).subscribe({next:r=>{const c=r.data;if(c.estado!==EstadoCotizacion.Borrador){void this.router.navigate(['/cotizaciones',id]);return}this.form.patchValue({clienteId:c.clienteId,observaciones:c.observaciones??''});this.detalles.clear();c.detalles.forEach(d=>this.detalles.push(this.grupo(d)));this.loading.set(false)},error:()=>{this.loading.set(false);this.snack.open('No fue posible cargar la cotización.','Cerrar',{duration:4000})}})}guardar(){if(this.form.invalid||!this.detalles.length){this.form.markAllAsTouched();return}const v=this.form.getRawValue();const detalles=(v.detalles as CotizacionDetalleInput[]).map(d=>({id:d.id??undefined,productoId:Number(d.productoId),productoVarianteId:d.productoVarianteId??null,cantidad:Number(d.cantidad),precioUnitario:Number(d.precioUnitario)}));this.saving.set(true);const q=this.editando&&this.id?this.svc.update(this.id,{id:this.id,clienteId:Number(v.clienteId),observaciones:v.observaciones?.trim()||null,detalles}):this.svc.create({clienteId:Number(v.clienteId),observaciones:v.observaciones?.trim()||null,detalles});q.subscribe({next:r=>{this.saving.set(false);void this.router.navigate(['/cotizaciones',r.data.id])},error:e=>{this.saving.set(false);this.snack.open(e.error?.detail||e.error?.message||'No fue posible guardar.','Cerrar',{duration:5000})}})}}
@Component({selector:'app-cotizacion-detail',standalone:true,imports:UI,template:`<section class="page">@if(loading()){<div class="center"><mat-spinner diameter="40"/></div>}@else if(cotizacion();as c){<header><div><h1>Cotización COT-{{c.id}}</h1><p>{{c.clienteNombreSnapshot}} · {{nombre(c.estado)}}</p></div><a mat-stroked-button routerLink="/cotizaciones">Volver</a></header><div class="actions">@if(c.estado===EstadoCotizacion.Borrador&&puede('Editar')){<a mat-stroked-button [routerLink]="['/cotizaciones',c.id,'editar']">Editar</a>}@if(c.estado===EstadoCotizacion.Borrador&&puede('Confirmar')){<button mat-flat-button color="primary" (click)="accion('enviar')">Enviar</button>}@if(c.estado===EstadoCotizacion.Enviada&&puede('Aprobar')){<button mat-flat-button color="primary" (click)="accion('aceptar')">Aceptar</button>}@if(c.estado===EstadoCotizacion.Enviada&&puede('Rechazar')){<button mat-stroked-button color="warn" (click)="rechazar()">Rechazar</button>}@if(c.estado===EstadoCotizacion.Aceptada&&puede('Confirmar')){<button mat-flat-button color="primary" (click)="accion('convertir')">Convertir</button>}@if(puede('Duplicar')){<button mat-stroked-button (click)="accion('duplicar')">Duplicar</button>}</div><mat-card><mat-card-content><p><strong>Cliente:</strong> {{c.clienteNombreSnapshot}}</p><p><strong>Documento:</strong> {{c.clienteDocumentoSnapshot||'—'}}</p><p><strong>Total:</strong> {{c.total|number:'1.2-2'}}</p>@if(c.observaciones){<p><strong>Observaciones:</strong> {{c.observaciones}}</p>}@if(c.motivoRechazo){<p><strong>Motivo rechazo:</strong> {{c.motivoRechazo}}</p>}<div class="table"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio</th><th>Total</th></tr></thead><tbody>@for(d of c.detalles;track d.id){<tr><td>{{d.productoNombreSnapshot||('Producto #'+d.productoId)}}</td><td>{{d.cantidad|number:'1.0-4'}}</td><td>{{d.precioUnitario|number:'1.2-4'}}</td><td>{{d.total|number:'1.2-4g'}}</td></tr>}</tbody></table></div></mat-card-content></mat-card>}</section>`,changeDetection: ChangeDetectionStrategy.Eager,
styles:[`.page{max-width:1100px;margin:auto;padding:16px}header,.actions{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:16px}.actions{justify-content:flex-start;flex-wrap:wrap}.center{text-align:center;padding:36px}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:10px;text-align:left;border-bottom:1px solid var(--color-border)}@media(max-width:700px){header{align-items:flex-start;flex-direction:column}}`]})
export class CotizacionDetailComponent implements OnInit{private svc=inject(CotizacionService);private permisos=inject(PermisosRuntimeService);private route=inject(ActivatedRoute);private router=inject(Router);private snack=inject(MatSnackBar);private alerts=inject(AppAlertService);readonly cotizacion=signal<Cotizacion|null>(null);readonly loading=signal(true);readonly EstadoCotizacion=EstadoCotizacion;ngOnInit(){const id=Number(this.route.snapshot.paramMap.get('id'));if(!Number.isInteger(id)||id<=0){void this.router.navigate(['/cotizaciones']);return}this.cargar(id)}puede(a:string){return this.permisos.puede('Ventas',a)}nombre(e:EstadoCotizacion){return estado(e)}private cargar(id:number){this.loading.set(true);this.svc.getById(id).subscribe({next:r=>{this.cotizacion.set(r.data);this.loading.set(false)},error:()=>{this.loading.set(false);this.snack.open('No fue posible cargar la cotización.','Cerrar',{duration:4000})}})}accion(a:'enviar'|'aceptar'|'convertir'|'duplicar'){const c=this.cotizacion();if(!c)return;const q=a==='enviar'?this.svc.enviar(c.id):a==='aceptar'?this.svc.aceptar(c.id):a==='convertir'?this.svc.convertir(c.id):this.svc.duplicar(c.id);q.subscribe({next:r=>{if(a==='duplicar'){void this.router.navigate(['/cotizaciones',r.data.id]);return}this.cargar(c.id)},error:e=>this.snack.open(e.error?.detail||e.error?.message||'No fue posible completar la acción.','Cerrar',{duration:5000})})}async rechazar():Promise<void>{const c=this.cotizacion();if(!c)return;const motivo=await this.alerts.solicitarTexto({titulo:'Rechazar cotización',mensaje:'Indica el motivo del rechazo.',entrada:{etiqueta:'Motivo',requerida:true},tipo:'peligro',confirmarTexto:'Rechazar',cancelarTexto:'Cancelar'});if(!motivo)return;this.svc.rechazar(c.id,motivo).subscribe({next:()=>this.cargar(c.id),error:e=>this.snack.open(e.error?.detail||e.error?.message||'No fue posible rechazar.','Cerrar',{duration:5000})})}}
