// <auto-generated />
using Solqaryn.Domain.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart25(ModelBuilder modelBuilder)
        {
            var preparacion = modelBuilder.Entity<PreparacionPedidoVenta>();
            preparacion.ToTable("PreparacionesPedidoVenta", table => table.HasCheckConstraint("CK_PreparacionesPedidoVenta_Estado", "`Estado` IN (1, 2, 3, 4, 5, 6)"));
            preparacion.Property(x => x.Estado).HasConversion<int>().IsRequired();
            preparacion.Property(x => x.MotivoCancelacion).HasMaxLength(1000);
            preparacion.HasIndex(x => x.PedidoVentaId).IsUnique().HasDatabaseName("UX_PreparacionesPedidoVenta_PedidoVentaId");
            preparacion.HasIndex(x => x.ReservaInventarioId).IsUnique().HasDatabaseName("UX_PreparacionesPedidoVenta_ReservaInventarioId");
            preparacion.HasIndex(x => x.Estado).HasDatabaseName("IX_PreparacionesPedidoVenta_Estado");
            preparacion.HasOne(x => x.PedidoVenta).WithMany().HasForeignKey(x => x.PedidoVentaId).OnDelete(DeleteBehavior.Restrict);
            preparacion.HasOne("Solqaryn.Domain.Entities.ReservaInventario", "ReservaInventario").WithMany().HasForeignKey("ReservaInventarioId").OnDelete(DeleteBehavior.Restrict);
            preparacion.HasMany(x => x.Detalles).WithOne(x => x.PreparacionPedidoVenta).HasForeignKey(x => x.PreparacionPedidoVentaId).OnDelete(DeleteBehavior.Cascade);

            var detalle = modelBuilder.Entity<PreparacionPedidoVentaDetalle>();
            detalle.ToTable("PreparacionPedidoVentaDetalles", table => table.HasCheckConstraint("CK_PreparacionPedidoVentaDetalles_CantidadPreparar", "`CantidadPreparar` > 0"));
            detalle.Property(x => x.ProductoSkuSnapshot).HasMaxLength(120);
            detalle.Property(x => x.ProductoMarcaSnapshot).HasMaxLength(150);
            detalle.Property(x => x.ProductoModeloSnapshot).HasMaxLength(150);
            detalle.Property(x => x.ProductoColorSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoTallaSnapshot).HasMaxLength(100);
            detalle.Property<int>("UbicacionNormalizada").HasComputedColumnSql("COALESCE(`UbicacionAlmacenId`, 0)", stored: true);
            detalle.HasIndex(new[] { nameof(PreparacionPedidoVentaDetalle.PreparacionPedidoVentaId), nameof(PreparacionPedidoVentaDetalle.ProductoVarianteId), nameof(PreparacionPedidoVentaDetalle.AlmacenId), "UbicacionNormalizada" }).IsUnique().HasDatabaseName("UX_PreparacionPedidoVentaDetalles_ClaveFisica");
            detalle.HasIndex(x => x.ProductoVarianteId).HasDatabaseName("IX_PreparacionPedidoVentaDetalles_ProductoVarianteId");
            detalle.HasIndex(x => x.AlmacenId).HasDatabaseName("IX_PreparacionPedidoVentaDetalles_AlmacenId");

            // ProductoVariante, Almacen and UbicacionAlmacen are historical shared-type identities
            // in this snapshot baseline. Preserve the foreign keys by entity-type name instead of
            // coercing them to their modern CLR types, which would create duplicate EF identities.
            ((Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder)detalle)
                .HasOne("Solqaryn.Domain.Entities.ProductoVariante", null).WithMany()
                .HasForeignKey("ProductoVarianteId").OnDelete(DeleteBehavior.Restrict);
            ((Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder)detalle)
                .HasOne("Solqaryn.Domain.Entities.Almacen", null).WithMany()
                .HasForeignKey("AlmacenId").OnDelete(DeleteBehavior.Restrict);
            ((Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder)detalle)
                .HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", null).WithMany()
                .HasForeignKey("AlmacenId", "UbicacionAlmacenId")
                .HasPrincipalKey("AlmacenId", "Id")
                .OnDelete(DeleteBehavior.Restrict);
        }
    }
}