// <auto-generated />
using Solqaryn.Domain.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart23(ModelBuilder modelBuilder)
        {
            var cotizacion = modelBuilder.Entity<Cotizacion>();

            cotizacion.ToTable("Cotizaciones", table =>
            {
                table.HasCheckConstraint("CK_Cotizaciones_Estado", "`Estado` IN (0, 1, 2, 3, 4)");
            });

            cotizacion.Property(x => x.Id).ValueGeneratedOnAdd();
            cotizacion.Property(x => x.ClienteNombreSnapshot).IsRequired().HasMaxLength(200);
            cotizacion.Property(x => x.ClienteDocumentoSnapshot).HasMaxLength(50);
            cotizacion.Property(x => x.Estado).HasConversion<int>().IsRequired();
            cotizacion.Property(x => x.Observaciones).HasMaxLength(1000);
            cotizacion.Property(x => x.MotivoRechazo).HasMaxLength(500);
            cotizacion.Property(x => x.CreadoPorNombreUsuario).HasMaxLength(150);
            cotizacion.Property(x => x.ActualizadoPorNombreUsuario).HasMaxLength(150);
            cotizacion.Ignore(x => x.Total);
            cotizacion.Ignore(x => x.EsEditable);

            cotizacion.HasIndex(x => x.ClienteId)
                .HasDatabaseName("IX_Cotizaciones_ClienteId");
            cotizacion.HasIndex(x => x.Estado)
                .HasDatabaseName("IX_Cotizaciones_Estado");

            cotizacion.HasOne("Solqaryn.Domain.Entities.Cliente", null)
                .WithMany()
                .HasForeignKey("ClienteId")
                .OnDelete(DeleteBehavior.Restrict);

            cotizacion.HasMany(x => x.Detalles)
                .WithOne(x => x.Cotizacion)
                .HasForeignKey(x => x.CotizacionId)
                .OnDelete(DeleteBehavior.Cascade);

            var detalle = modelBuilder.Entity<CotizacionDetalle>();

            detalle.ToTable("CotizacionDetalles", table =>
            {
                table.HasCheckConstraint("CK_CotizacionDetalles_Cantidad_Positiva", "`Cantidad` > 0");
                table.HasCheckConstraint("CK_CotizacionDetalles_PrecioUnitario_NoNegativo", "`PrecioUnitario` >= 0");
            });

            detalle.Property(x => x.Id).ValueGeneratedOnAdd();
            detalle.Property(x => x.ProductoSkuSnapshot).HasMaxLength(80);
            detalle.Property(x => x.ProductoNombreSnapshot).HasMaxLength(150);
            detalle.Property(x => x.ProductoMarcaSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoModeloSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoColorSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoTallaSnapshot).HasMaxLength(100);
            detalle.Property(x => x.Cantidad).HasPrecision(18, 4);
            detalle.Property(x => x.PrecioUnitario).HasPrecision(18, 4);
            detalle.Property(x => x.CreadoPorNombreUsuario).HasMaxLength(150);
            detalle.Property(x => x.ActualizadoPorNombreUsuario).HasMaxLength(150);
            detalle.Ignore(x => x.Total);

            detalle.HasIndex(x => new { x.CotizacionId, x.ProductoId, x.ProductoVarianteId })
                .HasDatabaseName("IX_CotizacionDetalles_Cotizacion_Producto_Variante");
            detalle.HasIndex(x => x.ProductoId)
                .HasDatabaseName("IX_CotizacionDetalles_ProductoId");
            detalle.HasIndex(x => x.ProductoVarianteId)
                .HasDatabaseName("IX_CotizacionDetalles_ProductoVarianteId");

            detalle.HasOne("Solqaryn.Domain.Entities.Producto", null)
                .WithMany()
                .HasForeignKey("ProductoId")
                .OnDelete(DeleteBehavior.Restrict);
            detalle.HasOne("Solqaryn.Domain.Entities.ProductoVariante", null)
                .WithMany()
                .HasForeignKey("ProductoVarianteId")
                .OnDelete(DeleteBehavior.Restrict);
        }
    }
}
