// <auto-generated />
using Solqaryn.Domain.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart19(ModelBuilder modelBuilder)
        {
            var devolucion = modelBuilder.Entity<DevolucionProveedor>();

            devolucion.ToTable("DevolucionesProveedor", table =>
            {
                table.HasCheckConstraint("CK_DevolucionesProveedor_IdsValidos",
                    "ProveedorId > 0 AND OrdenCompraId > 0 AND RecepcionCompraId > 0 AND FacturaProveedorId > 0");
                table.HasCheckConstraint("CK_DevolucionesProveedor_EstadoValido",
                    "Estado IN (1, 2, 3)");
                table.HasCheckConstraint("CK_DevolucionesProveedor_MonedaIso3",
                    "CHAR_LENGTH(TRIM(Moneda)) = 3");
                table.HasCheckConstraint("CK_DevolucionesProveedor_IdempotenciaAtomica",
                    "(IdempotencyKey IS NULL AND IdempotencyFingerprint IS NULL) OR (IdempotencyKey IS NOT NULL AND IdempotencyFingerprint IS NOT NULL)");
            });

            devolucion.Property(x => x.Id).ValueGeneratedOnAdd();
            devolucion.Property(x => x.NumeroDevolucion).HasMaxLength(80).IsRequired();
            devolucion.Property(x => x.ProveedorNombreSnapshot).HasMaxLength(250).IsRequired();
            devolucion.Property(x => x.Moneda).HasMaxLength(3).IsRequired();
            devolucion.Property(x => x.Motivo).HasMaxLength(500).IsRequired();
            devolucion.Property(x => x.Observaciones).HasMaxLength(1000);
            devolucion.Property(x => x.IdempotencyKey).HasMaxLength(128);
            devolucion.Property(x => x.IdempotencyFingerprint).HasMaxLength(64);
            devolucion.Property(x => x.Estado).HasConversion<int>().IsRequired();
            devolucion.Property(x => x.ConfirmadaPorNombreSnapshot).HasMaxLength(150);
            devolucion.Property(x => x.MotivoAnulacion).HasMaxLength(500);
            devolucion.Property(x => x.CreadoPorNombreUsuario).HasMaxLength(150);
            devolucion.Property(x => x.ActualizadoPorNombreUsuario).HasMaxLength(150);

            devolucion.HasIndex(x => x.NumeroDevolucion)
                .IsUnique()
                .HasDatabaseName("UX_DevolucionesProveedor_NumeroDevolucion");
            devolucion.HasIndex(x => new { x.ProveedorId, x.Estado })
                .HasDatabaseName("IX_DevolucionesProveedor_Proveedor_Estado");
            devolucion.HasIndex(x => x.OrdenCompraId)
                .HasDatabaseName("IX_DevolucionesProveedor_OrdenCompraId");
            devolucion.HasIndex(x => x.RecepcionCompraId)
                .HasDatabaseName("IX_DevolucionesProveedor_RecepcionCompraId");
            devolucion.HasIndex(x => x.FacturaProveedorId)
                .HasDatabaseName("IX_DevolucionesProveedor_FacturaProveedorId");
            devolucion.HasIndex(x => x.IdempotencyKey)
                .IsUnique()
                .HasDatabaseName("UX_DevolucionesProveedor_IdempotencyKey");

            devolucion.HasOne("Solqaryn.Domain.Entities.Proveedor", null)
                .WithMany()
                .HasForeignKey("ProveedorId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_DevolucionesProveedor_Proveedores_ProveedorId");
            devolucion.HasOne("Solqaryn.Domain.Entities.OrdenCompra", null)
                .WithMany()
                .HasForeignKey("OrdenCompraId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_DevolucionesProveedor_OrdenesCompra_OrdenCompraId");
            devolucion.HasOne("Solqaryn.Domain.Entities.RecepcionCompra", null)
                .WithMany()
                .HasForeignKey("RecepcionCompraId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_DevolucionesProveedor_RecepcionesCompra_RecepcionCompraId");
            devolucion.HasOne("Solqaryn.Domain.Entities.FacturaProveedor", null)
                .WithMany()
                .HasForeignKey("FacturaProveedorId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_DevolucionesProveedor_FacturasProveedor_FacturaProveedorId");

            devolucion.HasMany(x => x.Detalles)
                .WithOne()
                .HasForeignKey(x => x.DevolucionProveedorId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_DevolucionProveedorDetalles_DevolucionesProveedor_DevolucionProveedorId");

            var detalle = modelBuilder.Entity<DevolucionProveedorDetalle>();

            detalle.ToTable("DevolucionProveedorDetalles", table =>
            {
                table.HasCheckConstraint("CK_DevolucionProveedorDetalles_IdsValidos",
                    "DevolucionProveedorId > 0 AND RecepcionCompraDetalleId > 0 AND OrdenCompraDetalleId > 0 AND ProductoId > 0 AND AlmacenId > 0");
                table.HasCheckConstraint("CK_DevolucionProveedorDetalles_CantidadPositiva", "Cantidad > 0");
                table.HasCheckConstraint("CK_DevolucionProveedorDetalles_CostosNoNegativos",
                    "CostoUnitarioSnapshot >= 0 AND ImpuestoUnitarioSnapshot >= 0");
            });

            detalle.Property(x => x.Id).ValueGeneratedOnAdd();
            detalle.Property(x => x.Cantidad).HasPrecision(18, 4).IsRequired();
            detalle.Property(x => x.CostoUnitarioSnapshot).HasPrecision(18, 4).IsRequired();
            detalle.Property(x => x.ImpuestoUnitarioSnapshot).HasPrecision(18, 4).IsRequired();
            detalle.Property(x => x.ProductoSkuSnapshot).HasMaxLength(120);
            detalle.Property(x => x.ProductoNombreSnapshot).HasMaxLength(250).IsRequired();
            detalle.Property(x => x.ProductoMarcaSnapshot).HasMaxLength(150);
            detalle.Property(x => x.ProductoModeloSnapshot).HasMaxLength(150);
            detalle.Property(x => x.ProductoColorSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoTallaSnapshot).HasMaxLength(100);
            detalle.Property(x => x.CreadoPorNombreUsuario).HasMaxLength(150);
            detalle.Property(x => x.ActualizadoPorNombreUsuario).HasMaxLength(150);

            detalle.HasIndex(x => new { x.DevolucionProveedorId, x.RecepcionCompraDetalleId })
                .IsUnique()
                .HasDatabaseName("UX_DevolucionProveedorDetalles_Devolucion_RecepcionDetalle");
            detalle.HasIndex(x => x.OrdenCompraDetalleId)
                .HasDatabaseName("IX_DevolucionProveedorDetalles_OrdenCompraDetalleId");
            detalle.HasIndex(x => x.ProductoId)
                .HasDatabaseName("IX_DevolucionProveedorDetalles_ProductoId");
            detalle.HasIndex(x => x.ProductoVarianteId)
                .HasDatabaseName("IX_DevolucionProveedorDetalles_ProductoVarianteId");
            detalle.HasIndex(x => x.AlmacenId)
                .HasDatabaseName("IX_DevolucionProveedorDetalles_AlmacenId");
            detalle.HasIndex(x => x.UbicacionAlmacenId)
                .HasDatabaseName("IX_DevolucionProveedorDetalles_UbicacionAlmacenId");

            detalle.HasOne("Solqaryn.Domain.Entities.RecepcionCompraDetalle", null)
                .WithMany()
                .HasForeignKey("RecepcionCompraDetalleId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_DevolucionProveedorDetalles_RecepcionCompraDetalles_RecepcionCompraDetalleId");
            detalle.HasOne("Solqaryn.Domain.Entities.OrdenCompraDetalle", null)
                .WithMany()
                .HasForeignKey("OrdenCompraDetalleId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_DevolucionProveedorDetalles_OrdenCompraDetalles_OrdenCompraDetalleId");
            detalle.HasOne("Solqaryn.Domain.Entities.Producto", null)
                .WithMany()
                .HasForeignKey("ProductoId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_DevolucionProveedorDetalles_Productos_ProductoId");
            detalle.HasOne("Solqaryn.Domain.Entities.ProductoVariante", null)
                .WithMany()
                .HasForeignKey("ProductoVarianteId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_DevolucionProveedorDetalles_ProductoVariantes_ProductoVarianteId");
            detalle.HasOne("Solqaryn.Domain.Entities.Almacen", null)
                .WithMany()
                .HasForeignKey("AlmacenId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_DevolucionProveedorDetalles_Almacenes_AlmacenId");
            detalle.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", null)
                .WithMany()
                .HasForeignKey("UbicacionAlmacenId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_DevolucionProveedorDetalles_UbicacionesAlmacen_UbicacionAlmacenId");
        }
    }
}
