// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    partial class AppDbContextModelSnapshot
    {
        /// <summary>
        /// N6.7.C — alinea el snapshot efectivo con la persistencia tenant-scoped
        /// de identidad/configuración de empresa sin reescribir el snapshot histórico.
        /// Se encadena desde el overlay N6.3.C, siguiendo el patrón aditivo existente.
        /// </summary>
        private static void ApplyN67CModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.Entity("Solqaryn.Domain.Entities.ConfigEmpresa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<bool>("CorreoConfigurado")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("CorreoNombreRemitente")
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)");

                b.Property<string>("CorreoRemitente")
                    .HasMaxLength(254)
                    .HasColumnType("varchar(254)");

                b.Property<string>("CorreoSecretoReferencia")
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("EmisionJson")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("longtext")
                    .HasDefaultValue("{}");

                b.Property<int>("EmpresaId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("ImpuestosJson")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("longtext")
                    .HasDefaultValue("{}");

                b.Property<string>("Moneda")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(3)
                    .HasColumnType("varchar(3)")
                    .HasDefaultValue("HNL");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasDefaultValue(1L);

                b.Property<string>("ZonaHoraria")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)")
                    .HasDefaultValue("America/Tegucigalpa");

                b.HasKey("Id");

                b.HasIndex("EmpresaId")
                    .IsUnique()
                    .HasDatabaseName("UX_ConfigEmpresas_EmpresaId");

                b.ToTable("ConfigEmpresas", null, t =>
                {
                    t.HasCheckConstraint("CK_ConfigEmpresas_Moneda", "CHAR_LENGTH(TRIM(`Moneda`)) = 3");
                    t.HasCheckConstraint("CK_ConfigEmpresas_Version", "`Version` > 0");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.Empresa", b =>
            {
                b.Property<string>("Direccion")
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<string>("LogoPublicId")
                    .HasMaxLength(250)
                    .HasColumnType("varchar(250)");

                b.Property<string>("LogoUrl")
                    .HasMaxLength(1000)
                    .HasColumnType("varchar(1000)");

                b.Property<string>("Rtn")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("RTN");

                b.HasIndex("Rtn")
                    .IsUnique()
                    .HasDatabaseName("UX_Empresas_RTN");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.PlantillaCorreoEmpresa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Activa")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("Asunto")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("varchar(250)");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("Cuerpo")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<int>("EmpresaId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("TipoPlantilla")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("varchar(80)");

                b.HasKey("Id");

                b.HasIndex("EmpresaId", "TipoPlantilla")
                    .IsUnique()
                    .HasDatabaseName("UX_PlantillasCorreoEmpresa_Empresa_Tipo");

                b.ToTable("PlantillasCorreoEmpresa", (string)null);
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.ConfigEmpresa", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Empresa", "Empresa")
                    .WithOne()
                    .HasForeignKey("Solqaryn.Domain.Entities.ConfigEmpresa", "EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Empresa");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.PlantillaCorreoEmpresa", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Empresa", "Empresa")
                    .WithMany()
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Empresa");
            });
#pragma warning restore 612, 618
        }
    }
}
