// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart8(ModelBuilder modelBuilder)
        {
            // ERP-N1.6.C — persistencia normalizada de transferencias internas.
            modelBuilder.Entity("Solqaryn.Domain.Entities.TransferenciaInventario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int>("AlmacenDestinoId").HasColumnType("int");
                b.Property<int>("AlmacenOrigenId").HasColumnType("int");
                b.Property<int?>("AprobadaPorUsuarioId").HasColumnType("int");
                b.Property<int?>("CanceladaPorUsuarioId").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<int?>("DespachadaPorUsuarioId").HasColumnType("int");
                b.Property<string>("Estado").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaAprobacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaCancelacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaDespacho").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaRecepcion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaSolicitud").HasColumnType("datetime(6)");
                b.Property<string>("MotivoCancelacion").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("Numero").IsRequired().HasMaxLength(30).HasColumnType("varchar(30)");
                b.Property<string>("Observaciones").HasMaxLength(1000).HasColumnType("varchar(1000)");
                b.Property<int?>("RecibidaPorUsuarioId").HasColumnType("int");
                b.Property<int?>("SolicitadaPorUsuarioId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("AlmacenDestinoId", "Estado").HasDatabaseName("IX_TransferenciasInventario_Destino_Estado");
                b.HasIndex("AlmacenOrigenId", "Estado").HasDatabaseName("IX_TransferenciasInventario_Origen_Estado");
                b.HasIndex("Estado", "FechaSolicitud").HasDatabaseName("IX_TransferenciasInventario_Estado_FechaSolicitud");
                b.HasIndex("Numero").IsUnique().HasDatabaseName("UX_TransferenciasInventario_Numero");

                b.ToTable("TransferenciasInventario", (string)null, t =>
                {
                    t.HasCheckConstraint("CK_TransferenciasInventario_AlmacenesDistintos", "`AlmacenOrigenId` <> `AlmacenDestinoId`");
                    t.HasCheckConstraint("CK_TransferenciasInventario_Estado_Valido", "`Estado` IN ('Borrador','Solicitada','Aprobada','EnTransito','Recibida','Cancelada')");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.TransferenciaInventarioDetalle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int>("CantidadAprobada").HasColumnType("int");
                b.Property<int>("CantidadDanada").HasColumnType("int");
                b.Property<int>("CantidadDespachada").HasColumnType("int");
                b.Property<int>("CantidadFaltante").HasColumnType("int");
                b.Property<int>("CantidadRecibida").HasColumnType("int");
                b.Property<int>("CantidadSobrante").HasColumnType("int");
                b.Property<int>("CantidadSolicitada").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<string>("ProductoColorSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("ProductoMarcaSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("ProductoModeloSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("ProductoSkuSnapshot").HasMaxLength(80).HasColumnType("varchar(80)");
                b.Property<string>("ProductoTallaSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("ProductoVarianteId").HasColumnType("int");
                b.Property<int>("TransferenciaInventarioId").HasColumnType("int");
                b.Property<int?>("UbicacionDestinoId").HasColumnType("int");
                b.Property<int?>("UbicacionOrigenId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("ProductoVarianteId", "TransferenciaInventarioId").HasDatabaseName("IX_TransferenciaInventarioDetalles_Variante_Transferencia");
                b.HasIndex("TransferenciaInventarioId").HasDatabaseName("IX_TransferenciaInventarioDetalles_TransferenciaId");
                b.HasIndex("UbicacionDestinoId").HasDatabaseName("IX_TransferenciaInventarioDetalles_UbicacionDestino");
                b.HasIndex("UbicacionOrigenId").HasDatabaseName("IX_TransferenciaInventarioDetalles_UbicacionOrigen");

                b.ToTable("TransferenciaInventarioDetalles", (string)null, t =>
                {
                    t.HasCheckConstraint("CK_TransferenciaInventarioDetalles_CantidadesNoNegativas", "`CantidadSolicitada` > 0 AND `CantidadAprobada` >= 0 AND `CantidadDespachada` >= 0 AND `CantidadRecibida` >= 0 AND `CantidadFaltante` >= 0 AND `CantidadSobrante` >= 0 AND `CantidadDanada` >= 0");
                    t.HasCheckConstraint("CK_TransferenciaInventarioDetalles_Aprobada", "`CantidadAprobada` <= `CantidadSolicitada`");
                    t.HasCheckConstraint("CK_TransferenciaInventarioDetalles_Despachada", "`CantidadDespachada` <= `CantidadAprobada`");
                    t.HasCheckConstraint("CK_TransferenciaInventarioDetalles_Recepcion", "`CantidadRecibida` + `CantidadFaltante` + `CantidadDanada` <= `CantidadDespachada`");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.TransferenciaInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Almacen", "AlmacenDestino")
                    .WithMany().HasForeignKey("AlmacenDestinoId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_TransferenciasInventario_Almacenes_Destino");
                b.HasOne("Solqaryn.Domain.Entities.Almacen", "AlmacenOrigen")
                    .WithMany().HasForeignKey("AlmacenOrigenId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_TransferenciasInventario_Almacenes_Origen");
                b.Navigation("AlmacenDestino");
                b.Navigation("AlmacenOrigen");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.TransferenciaInventarioDetalle", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", "ProductoVariante")
                    .WithMany().HasForeignKey("ProductoVarianteId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_TransferenciaInventarioDetalles_ProductoVariantes");
                b.HasOne("Solqaryn.Domain.Entities.TransferenciaInventario", "TransferenciaInventario")
                    .WithMany("Detalles").HasForeignKey("TransferenciaInventarioId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired()
                    .HasConstraintName("FK_TransferenciaInventarioDetalles_TransferenciasInventario");
                b.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", "UbicacionDestino")
                    .WithMany().HasForeignKey("UbicacionDestinoId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_TransferenciaInventarioDetalles_Ubicaciones_Destino");
                b.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", "UbicacionOrigen")
                    .WithMany().HasForeignKey("UbicacionOrigenId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_TransferenciaInventarioDetalles_Ubicaciones_Origen");
                b.Navigation("ProductoVariante");
                b.Navigation("TransferenciaInventario");
                b.Navigation("UbicacionDestino");
                b.Navigation("UbicacionOrigen");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.TransferenciaInventario", b =>
            {
                b.Navigation("Detalles");
            });
        }
    }
}
