// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart16(ModelBuilder modelBuilder)
        {
            // ERP-N2.3.D — RecepcionCompra como origen relacional tipado del Kardex.
            modelBuilder.Entity("Solqaryn.Domain.Entities.MovimientoInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.RecepcionCompra", null)
                    .WithMany()
                    .HasForeignKey("RecepcionCompraId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovInv_RecepcionCompraId_N23");
            });
        }
    }
}
