// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart17(ModelBuilder modelBuilder)
        {
            // ERP-N2.4.C — factura documental de proveedor.
            // No materializa recepción, stock, Kardex, costeo ni finanzas.
            modelBuilder.Entity("Solqaryn.Domain.Entities.FacturaProveedor", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int?>("AnuladaPorUsuarioId").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<int>("Estado").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaAnulacionUtc").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaEmisionUtc").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaRegistroUtc").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaVencimientoUtc").HasColumnType("datetime(6)");
                b.Property<string>("Moneda").IsRequired().HasMaxLength(3).HasColumnType("varchar(3)");
                b.Property<string>("MotivoAnulacion").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("NumeroFactura").IsRequired().HasMaxLength(80).HasColumnType("varchar(80)");
                b.Property<string>("Observaciones").HasMaxLength(1000).HasColumnType("varchar(1000)");
                b.Property<int>("OrdenCompraId").HasColumnType("int");
                b.Property<int>("ProveedorId").HasColumnType("int");
                b.Property<string>("ProveedorDocumentoSnapshot").HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<string>("ProveedorNombreSnapshot").IsRequired().HasMaxLength(250).HasColumnType("varchar(250)");
                b.Property<string>("ReferenciaFiscal").HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<string>("RegistradaPorNombreSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("RegistradaPorUsuarioId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("Estado", "FechaEmisionUtc").HasDatabaseName("IX_FacturasProveedor_Estado_FechaEmision");
                b.HasIndex("FechaVencimientoUtc").HasDatabaseName("IX_FacturasProveedor_FechaVencimiento");
                b.HasIndex("OrdenCompraId").HasDatabaseName("IX_FacturasProveedor_OrdenCompraId");
                b.HasIndex("ProveedorId", "NumeroFactura").IsUnique().HasDatabaseName("UX_FacturasProveedor_Proveedor_NumeroFactura");
                b.ToTable("FacturasProveedor", t =>
                {
                    t.HasCheckConstraint("CK_FacturasProveedor_IdsValidos", "ProveedorId > 0 AND OrdenCompraId > 0");
                    t.HasCheckConstraint("CK_FacturasProveedor_EstadoValido", "Estado IN (1, 2, 3)");
                    t.HasCheckConstraint("CK_FacturasProveedor_MonedaIso3", "CHAR_LENGTH(TRIM(Moneda)) = 3");
                    t.HasCheckConstraint("CK_FacturasProveedor_FechasValidas", "FechaVencimientoUtc IS NULL OR FechaVencimientoUtc >= FechaEmisionUtc");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.FacturaProveedorDetalle", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<decimal>("CantidadFacturada").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<decimal>("DescuentoSnapshot").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<int>("FacturaProveedorId").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<decimal>("ImpuestoSnapshot").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<string>("Observacion").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int>("OrdenCompraDetalleId").HasColumnType("int");
                b.Property<decimal>("PrecioUnitarioSnapshot").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<string>("ProductoColorSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("ProductoId").HasColumnType("int");
                b.Property<string>("ProductoMarcaSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoModeloSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoNombreSnapshot").IsRequired().HasMaxLength(250).HasColumnType("varchar(250)");
                b.Property<string>("ProductoSkuSnapshot").HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<string>("ProductoTallaSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int?>("ProductoVarianteId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("FacturaProveedorId").HasDatabaseName("IX_FacturaProveedorDetalles_FacturaProveedorId");
                b.HasIndex("FacturaProveedorId", "OrdenCompraDetalleId").IsUnique().HasDatabaseName("UX_FacturaProveedorDetalles_Factura_OrdenDetalle");
                b.HasIndex("OrdenCompraDetalleId");
                b.HasIndex("ProductoId");
                b.HasIndex("ProductoVarianteId");
                b.HasIndex("ProductoId", "ProductoVarianteId").HasDatabaseName("IX_FacturaProveedorDetalles_Producto_Variante");
                b.ToTable("FacturaProveedorDetalles", t =>
                {
                    t.HasCheckConstraint("CK_FacturaProveedorDetalles_IdsValidos", "OrdenCompraDetalleId > 0 AND ProductoId > 0 AND (ProductoVarianteId IS NULL OR ProductoVarianteId > 0)");
                    t.HasCheckConstraint("CK_FacturaProveedorDetalles_ImportesValidos", "CantidadFacturada > 0 AND PrecioUnitarioSnapshot >= 0 AND DescuentoSnapshot >= 0 AND ImpuestoSnapshot >= 0");
                    t.HasCheckConstraint("CK_FacturaProveedorDetalles_DescuentoValido", "DescuentoSnapshot <= CantidadFacturada * PrecioUnitarioSnapshot");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.FacturaProveedor", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.OrdenCompra", "OrdenCompra").WithMany()
                    .HasForeignKey("OrdenCompraId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_FacturasProveedor_OrdenesCompra_OrdenCompraId");
                b.HasOne("Solqaryn.Domain.Entities.Proveedor", "Proveedor").WithMany()
                    .HasForeignKey("ProveedorId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_FacturasProveedor_Proveedores_ProveedorId");
                b.Navigation("OrdenCompra");
                b.Navigation("Proveedor");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.FacturaProveedorDetalle", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.FacturaProveedor", "FacturaProveedor").WithMany("Detalles")
                    .HasForeignKey("FacturaProveedorId").OnDelete(DeleteBehavior.Cascade).IsRequired()
                    .HasConstraintName("FK_FacturaProveedorDetalles_FacturasProveedor_FacturaProveedorId");
                b.HasOne("Solqaryn.Domain.Entities.OrdenCompraDetalle", "OrdenCompraDetalle").WithMany()
                    .HasForeignKey("OrdenCompraDetalleId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_FacturaProveedorDetalles_OrdenCompraDetalles_OrdenCompraDetalleId");
                b.HasOne("Solqaryn.Domain.Entities.Producto", "Producto").WithMany()
                    .HasForeignKey("ProductoId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_FacturaProveedorDetalles_Productos_ProductoId");
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", "ProductoVariante").WithMany()
                    .HasForeignKey("ProductoVarianteId").OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_FacturaProveedorDetalles_ProductoVariantes_ProductoVarianteId");
                b.Navigation("FacturaProveedor");
                b.Navigation("OrdenCompraDetalle");
                b.Navigation("Producto");
                b.Navigation("ProductoVariante");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.FacturaProveedor", b => b.Navigation("Detalles"));
        }
    }
}
