// <auto-generated />
using Solqaryn.Domain.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart28(ModelBuilder modelBuilder)
        {
            var credito = modelBuilder.Entity<CreditoCliente>();
            credito.ToTable("CreditosCliente", table =>
            {
                table.HasCheckConstraint("CK_CreditosCliente_ClienteId", "`ClienteId` > 0");
                table.HasCheckConstraint("CK_CreditosCliente_Moneda", "CHAR_LENGTH(`Moneda`) = 3");
                table.HasCheckConstraint("CK_CreditosCliente_LimiteCredito", "`LimiteCredito` >= 0");
                table.HasCheckConstraint("CK_CreditosCliente_DiasCredito", "`DiasCredito` >= 0");
                table.HasCheckConstraint("CK_CreditosCliente_UmbralAlerta", "`UmbralAlertaPorcentaje` IS NULL OR (`UmbralAlertaPorcentaje` > 0 AND `UmbralAlertaPorcentaje` <= 100)");
                table.HasCheckConstraint("CK_CreditosCliente_MontoExcepcion", "`MontoExcepcion` IS NULL OR `MontoExcepcion` > 0");
            });

            credito.Property(x => x.Moneda).IsRequired().HasMaxLength(3);
            credito.Property(x => x.LimiteCredito).HasColumnType("decimal(18,4)").IsRequired();
            credito.Property(x => x.UmbralAlertaPorcentaje).HasColumnType("decimal(18,4)");
            credito.Property(x => x.MontoExcepcion).HasColumnType("decimal(18,4)");

            credito.HasIndex(x => x.ClienteId).HasDatabaseName("IX_CreditosCliente_ClienteId");

            // Cliente is a historical shared-type identity in this snapshot baseline.
            // Preserve the FK by entity-type name instead of coercing the relation to the modern CLR type.
            ((Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder)credito)
                .HasOne("Solqaryn.Domain.Entities.Cliente", null).WithMany()
                .HasForeignKey("ClienteId").OnDelete(DeleteBehavior.Restrict);
        }
    }
}
