// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    partial class AppDbContextModelSnapshot
    {
        /// <summary>
        /// N7.1.C — overlay de snapshot para la persistencia durable del outbox.
        /// </summary>
        private static void ApplyN71CModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.Entity("Solqaryn.Domain.Entities.MensajeOutbox", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClaveIdempotencia")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)");

                b.Property<string>("CorrelationId")
                    .HasMaxLength(160)
                    .HasColumnType("varchar(160)");

                b.Property<DateTime>("CreadoEnUtc")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("DisponibleDesdeUtc")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("EntregadoEnUtc")
                    .HasColumnType("datetime(6)");

                b.Property<int>("EmpresaId")
                    .HasColumnType("int");

                b.Property<int>("Estado")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<Guid>("EventoId")
                    .HasColumnType("char(36)");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("IdAgregado")
                    .HasMaxLength(160)
                    .HasColumnType("varchar(160)");

                b.Property<int>("Intentos")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<string>("PayloadJson")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<DateTime?>("ProcesandoDesdeUtc")
                    .HasColumnType("datetime(6)");

                b.Property<string>("TipoAgregado")
                    .HasMaxLength(120)
                    .HasColumnType("varchar(120)");

                b.Property<string>("TipoEvento")
                    .IsRequired()
                    .HasMaxLength(160)
                    .HasColumnType("varchar(160)");

                b.Property<string>("UltimoError")
                    .HasMaxLength(2000)
                    .HasColumnType("varchar(2000)");

                b.Property<DateTime?>("UltimoIntentoEnUtc")
                    .HasColumnType("datetime(6)");

                b.HasKey("Id");

                b.HasIndex("Estado", "DisponibleDesdeUtc", "Id")
                    .HasDatabaseName("IX_MensajesOutbox_Claim");

                b.HasIndex("EmpresaId", "ClaveIdempotencia")
                    .IsUnique()
                    .HasDatabaseName("UX_MensajesOutbox_EmpresaId_ClaveIdempotencia");

                b.HasIndex("EmpresaId", "Estado", "DisponibleDesdeUtc")
                    .HasDatabaseName("IX_MensajesOutbox_EmpresaId_Estado_Disponible");

                b.HasIndex("EventoId")
                    .IsUnique()
                    .HasDatabaseName("UX_MensajesOutbox_EventoId");

                b.ToTable("MensajesOutbox", null, t =>
                {
                    t.HasCheckConstraint("CK_MensajesOutbox_EmpresaId_Positivo", "`EmpresaId` > 0");
                    t.HasCheckConstraint("CK_MensajesOutbox_Estado_Valido", "`Estado` BETWEEN 0 AND 4");
                    t.HasCheckConstraint("CK_MensajesOutbox_Intentos_NoNegativo", "`Intentos` >= 0");
                    t.HasCheckConstraint("CK_MensajesOutbox_ClaveIdempotencia_NoVacia", "CHAR_LENGTH(TRIM(`ClaveIdempotencia`)) > 0");
                    t.HasCheckConstraint("CK_MensajesOutbox_Payload_NoVacio", "CHAR_LENGTH(TRIM(`PayloadJson`)) > 0");
                    t.HasCheckConstraint("CK_MensajesOutbox_TipoEvento_NoVacio", "CHAR_LENGTH(TRIM(`TipoEvento`)) > 0");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.MensajeOutbox", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Empresa", null)
                    .WithMany()
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
