// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart11(ModelBuilder modelBuilder)
        {
            // ERP-N1.9.C — lotes, series, vencimientos y política opt-in por variante.
            modelBuilder.Entity("Solqaryn.Domain.Entities.ProductoVariante", b =>
            {
                b.Property<bool>("ControlaLote").HasColumnType("tinyint(1)").HasDefaultValue(false);
                b.Property<bool>("ControlaNumeroSerie").HasColumnType("tinyint(1)").HasDefaultValue(false);
                b.Property<bool>("ControlaFechaVencimiento").HasColumnType("tinyint(1)").HasDefaultValue(false);
                b.Property<int?>("DiasAlertaVencimiento").HasColumnType("int");
                b.ToTable("ProductoVariantes", t =>
                {
                    t.HasCheckConstraint("CK_ProductoVariantes_TrazabilidadVencimiento", "`ControlaFechaVencimiento` = 0 OR `ControlaLote` = 1");
                    t.HasCheckConstraint("CK_ProductoVariantes_AlertaVencimiento", "(`DiasAlertaVencimiento` IS NULL AND `ControlaFechaVencimiento` = 0) OR (`ControlaFechaVencimiento` = 1 AND (`DiasAlertaVencimiento` IS NULL OR `DiasAlertaVencimiento` >= 0))");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.LoteInventario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<bool>("Activo").HasColumnType("tinyint(1)").HasDefaultValue(true);
                b.Property<string>("Codigo").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaFabricacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaVencimiento").HasColumnType("datetime(6)");
                b.Property<int>("ProductoVarianteId").HasColumnType("int");
                b.HasKey("Id");
                b.HasAlternateKey("ProductoVarianteId", "Id").HasName("AK_LotesInventario_Variante_Id");
                b.HasIndex("FechaVencimiento").HasDatabaseName("IX_LotesInventario_FechaVencimiento");
                b.HasIndex("ProductoVarianteId", "Codigo").IsUnique().HasDatabaseName("UX_LotesInventario_Variante_Codigo");
                b.ToTable("LotesInventario", t =>
                {
                    t.HasCheckConstraint("CK_LotesInventario_Fechas", "`FechaFabricacion` IS NULL OR `FechaVencimiento` IS NULL OR `FechaVencimiento` >= `FechaFabricacion`");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.SerieInventario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<int>("Estado").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<int?>("LoteInventarioId").HasColumnType("int");
                b.Property<string>("NumeroSerie").IsRequired().HasMaxLength(160).HasColumnType("varchar(160)");
                b.Property<int>("ProductoVarianteId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("NumeroSerie").IsUnique().HasDatabaseName("UX_SeriesInventario_NumeroSerie");
                b.HasIndex("ProductoVarianteId", "Estado").HasDatabaseName("IX_SeriesInventario_Variante_Estado");
                b.HasIndex("ProductoVarianteId", "LoteInventarioId").HasDatabaseName("IX_SeriesInventario_Variante_LoteInventarioId");
                b.ToTable("SeriesInventario");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.LoteInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", "ProductoVariante").WithMany()
                    .HasForeignKey("ProductoVarianteId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_LotesInventario_ProductoVariantes_ProductoVarianteId");
                b.Navigation("ProductoVariante");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.SerieInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.LoteInventario", "LoteInventario").WithMany()
                    .HasForeignKey("ProductoVarianteId", "LoteInventarioId")
                    .HasPrincipalKey("ProductoVarianteId", "Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_SeriesInventario_LotesInventario_Variante_Lote");
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", "ProductoVariante").WithMany()
                    .HasForeignKey("ProductoVarianteId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_SeriesInventario_ProductoVariantes_ProductoVarianteId");
                b.Navigation("LoteInventario");
                b.Navigation("ProductoVariante");
            });
        }
    }
}
