// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    partial class AppDbContextModelSnapshot
    {
        /// <summary>
        /// Overlay de snapshot para Plan, PlanLimite, Suscripcion y, desde N6.10.C,
        /// PlanModulo. Conserva el snapshot canonico historico y deja verificable
        /// el modelo relacional SaaS sin reescribir el snapshot monolitico previo.
        /// </summary>
        private static void ApplyN69CModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.Entity("Solqaryn.Domain.Entities.Plan", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Activo")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true);

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("varchar(80)");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)");

                b.HasKey("Id");

                b.HasAlternateKey("Id", "Codigo")
                    .HasName("AK_Planes_Id_Codigo");

                b.HasIndex("Codigo")
                    .IsUnique()
                    .HasDatabaseName("UX_Planes_Codigo");

                b.ToTable("Planes", (string)null);
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.Suscripcion", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<int>("EmpresaId")
                    .HasColumnType("int");

                b.Property<int>("Estado")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("FinUtc")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("InicioUtc")
                    .HasColumnType("datetime(6)");

                b.Property<int>("PlanId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("EmpresaId", "Estado")
                    .HasDatabaseName("IX_Suscripciones_EmpresaId_Estado");

                b.HasIndex("EmpresaId", "InicioUtc")
                    .HasDatabaseName("IX_Suscripciones_EmpresaId_InicioUtc");

                b.HasIndex("PlanId", "Estado")
                    .HasDatabaseName("IX_Suscripciones_PlanId_Estado");

                b.ToTable("Suscripciones", (string)null);
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.PlanModulo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Activo")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true);

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("ModuloClave")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("varchar(120)");

                b.Property<string>("PlanCodigo")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("varchar(80)");

                b.Property<int>("PlanId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("PlanId", "ModuloClave")
                    .IsUnique()
                    .HasDatabaseName("UX_PlanModulos_PlanId_ModuloClave");

                b.HasIndex("PlanId", "PlanCodigo")
                    .HasDatabaseName("IX_PlanModulos_PlanId_PlanCodigo");

                b.ToTable("PlanModulos", (string)null);
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.Plan", b =>
            {
                b.OwnsMany("Solqaryn.Domain.Entities.PlanLimite", "Limites", b1 =>
                {
                    b1.Property<int>("PlanId")
                        .HasColumnType("int");

                    b1.Property<string>("Clave")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b1.Property<int?>("ValorMaximo")
                        .HasColumnType("int");

                    b1.HasKey("PlanId", "Clave");

                    b1.HasIndex("PlanId")
                        .HasDatabaseName("IX_PlanLimites_PlanId");

                    b1.ToTable("PlanLimites", (string)null);

                    b1.WithOwner()
                        .HasForeignKey("PlanId");
                });

                b.Navigation("Limites");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.Suscripcion", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Empresa", null)
                    .WithMany()
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Solqaryn.Domain.Entities.Plan", null)
                    .WithMany()
                    .HasForeignKey("PlanId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.PlanModulo", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Plan", null)
                    .WithMany()
                    .HasForeignKey("PlanId", "PlanCodigo")
                    .HasPrincipalKey("Id", "Codigo")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });
            ApplyN71CModel(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
