// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart12(ModelBuilder modelBuilder)
        {
            // ERP-N1.10.C — política de costeo, capas FIFO, estándar y evidencia histórica.
            modelBuilder.Entity("Solqaryn.Domain.Entities.PoliticaCosteoInventario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<int>("EmpresaConfiguracionId").HasColumnType("int");
                b.Property<int?>("EmpresaConfiguracionVigenteId").ValueGeneratedOnAddOrUpdate().HasColumnType("int")
                    .HasComputedColumnSql("CASE WHEN `VigenteHastaUtc` IS NULL THEN `EmpresaConfiguracionId` ELSE NULL END", true);
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<int>("Metodo").HasColumnType("int");
                b.Property<string>("Motivo").IsRequired().HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<DateTime>("VigenteDesdeUtc").HasColumnType("datetime(6)");
                b.Property<DateTime?>("VigenteHastaUtc").HasColumnType("datetime(6)");
                b.HasKey("Id");
                b.HasIndex("EmpresaConfiguracionId", "VigenteDesdeUtc").HasDatabaseName("IX_PoliticasCosteo_Empresa_Vigencia");
                b.HasIndex("EmpresaConfiguracionVigenteId").IsUnique().HasDatabaseName("UX_PoliticasCosteo_Empresa_Vigente");
                b.ToTable("PoliticasCosteoInventario", t =>
                {
                    t.HasCheckConstraint("CK_PoliticasCosteo_Metodo", "`Metodo` IN (1,2,3)");
                    t.HasCheckConstraint("CK_PoliticasCosteo_Vigencia", "`VigenteHastaUtc` IS NULL OR `VigenteHastaUtc` > `VigenteDesdeUtc`");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.CostoEstandarInventario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<decimal>("CostoUnitario").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<string>("Motivo").IsRequired().HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int>("ProductoVarianteId").HasColumnType("int");
                b.Property<int?>("ProductoVarianteVigenteId").ValueGeneratedOnAddOrUpdate().HasColumnType("int")
                    .HasComputedColumnSql("CASE WHEN `VigenteHastaUtc` IS NULL THEN `ProductoVarianteId` ELSE NULL END", true);
                b.Property<DateTime>("VigenteDesdeUtc").HasColumnType("datetime(6)");
                b.Property<DateTime?>("VigenteHastaUtc").HasColumnType("datetime(6)");
                b.HasKey("Id");
                b.HasAlternateKey("ProductoVarianteId", "Id").HasName("AK_CostosEstandar_Variante_Id");
                b.HasIndex("ProductoVarianteId", "VigenteDesdeUtc").HasDatabaseName("IX_CostosEstandar_Variante_Vigencia");
                b.HasIndex("ProductoVarianteVigenteId").IsUnique().HasDatabaseName("UX_CostosEstandar_Variante_Vigente");
                b.ToTable("CostosEstandarInventario", t =>
                {
                    t.HasCheckConstraint("CK_CostosEstandar_Costo", "`CostoUnitario` >= 0");
                    t.HasCheckConstraint("CK_CostosEstandar_Vigencia", "`VigenteHastaUtc` IS NULL OR `VigenteHastaUtc` > `VigenteDesdeUtc`");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.CapaCostoInventario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int>("AlmacenId").HasColumnType("int");
                b.Property<int?>("CapaCostoOrigenId").HasColumnType("int");
                b.Property<int>("CantidadOriginal").HasColumnType("int");
                b.Property<int>("CantidadRestante").HasColumnType("int");
                b.Property<string>("CorrelationId").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<decimal>("CostoUnitario").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<bool>("EsApertura").HasColumnType("tinyint(1)").HasDefaultValue(false);
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaOrigenUtc").HasColumnType("datetime(6)");
                b.Property<string>("MotivoApertura").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int?>("MovimientoInventarioOrigenId").HasColumnType("int");
                b.Property<int>("ProductoVarianteId").HasColumnType("int");
                b.Property<int?>("UbicacionAlmacenId").HasColumnType("int");
                b.HasKey("Id");
                b.HasAlternateKey("ProductoVarianteId", "Id").HasName("AK_CapasCosto_Variante_Id");
                b.HasIndex("AlmacenId", "UbicacionAlmacenId").HasDatabaseName("IX_CapasCosto_Almacen_Ubicacion");
                b.HasIndex("MovimientoInventarioOrigenId").HasDatabaseName("IX_CapasCosto_MovimientoOrigen");
                b.HasIndex("ProductoVarianteId", "AlmacenId", "UbicacionAlmacenId", "FechaOrigenUtc", "Id").HasDatabaseName("IX_CapasCosto_FIFO");
                b.HasIndex("ProductoVarianteId", "CapaCostoOrigenId").HasDatabaseName("IX_CapasCosto_Linaje");
                b.ToTable("CapasCostoInventario", t =>
                {
                    t.HasCheckConstraint("CK_CapasCosto_Cantidades", "`CantidadOriginal` > 0 AND `CantidadRestante` >= 0 AND `CantidadRestante` <= `CantidadOriginal`");
                    t.HasCheckConstraint("CK_CapasCosto_Costo", "`CostoUnitario` >= 0");
                    t.HasCheckConstraint("CK_CapasCosto_Origen", "(`EsApertura` = 1 AND `MovimientoInventarioOrigenId` IS NULL AND `CapaCostoOrigenId` IS NULL AND `MotivoApertura` IS NOT NULL) OR (`EsApertura` = 0 AND `MovimientoInventarioOrigenId` IS NOT NULL AND `MotivoApertura` IS NULL)");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.AsignacionCostoMovimientoInventario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int?>("CapaCostoInventarioId").HasColumnType("int");
                b.Property<int>("Cantidad").HasColumnType("int");
                b.Property<string>("CorrelationId").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<decimal>("CostoUnitario").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<int>("Metodo").HasColumnType("int");
                b.Property<int>("MovimientoInventarioId").HasColumnType("int");
                b.Property<int>("ProductoVarianteId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("MovimientoInventarioId").HasDatabaseName("IX_AsignacionesCosto_Movimiento");
                b.HasIndex("ProductoVarianteId", "CapaCostoInventarioId").HasDatabaseName("IX_AsignacionesCosto_Capa");
                b.ToTable("AsignacionesCostoMovimientoInventario", t =>
                {
                    t.HasCheckConstraint("CK_AsignacionesCosto_Cantidad", "`Cantidad` > 0");
                    t.HasCheckConstraint("CK_AsignacionesCosto_CapaPorMetodo", "(`Metodo` = 2 AND `CapaCostoInventarioId` IS NOT NULL) OR (`Metodo` <> 2 AND `CapaCostoInventarioId` IS NULL)");
                    t.HasCheckConstraint("CK_AsignacionesCosto_Costo", "`CostoUnitario` >= 0");
                    t.HasCheckConstraint("CK_AsignacionesCosto_Metodo", "`Metodo` IN (1,2,3)");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.VariacionCostoEstandarInventario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int>("Cantidad").HasColumnType("int");
                b.Property<int>("CostoEstandarInventarioId").HasColumnType("int");
                b.Property<decimal>("CostoEstandarUnitario").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<decimal>("CostoRealUnitario").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<string>("CorrelationId").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<int>("MovimientoInventarioId").HasColumnType("int");
                b.Property<int>("ProductoVarianteId").HasColumnType("int");
                b.Property<decimal>("VariacionTotal").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.HasKey("Id");
                b.HasIndex("MovimientoInventarioId").HasDatabaseName("IX_VariacionesCostoEstandar_Movimiento");
                b.HasIndex("ProductoVarianteId", "CostoEstandarInventarioId").HasDatabaseName("IX_VariacionesCostoEstandar_Version");
                b.ToTable("VariacionesCostoEstandarInventario", t =>
                {
                    t.HasCheckConstraint("CK_VariacionesCostoEstandar_Cantidad", "`Cantidad` > 0");
                    t.HasCheckConstraint("CK_VariacionesCostoEstandar_Costos", "`CostoRealUnitario` >= 0 AND `CostoEstandarUnitario` >= 0");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.PoliticaCosteoInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.EmpresaConfiguracion", null).WithMany()
                    .HasForeignKey("EmpresaConfiguracionId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_PoliticasCosteo_EmpresaConfiguracion");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.CostoEstandarInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", null).WithMany()
                    .HasForeignKey("ProductoVarianteId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_CostosEstandar_ProductoVariantes");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.CapaCostoInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Almacen", null).WithMany()
                    .HasForeignKey("AlmacenId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_CapasCosto_Almacenes");
                b.HasOne("Solqaryn.Domain.Entities.CapaCostoInventario", null).WithMany()
                    .HasForeignKey("ProductoVarianteId", "CapaCostoOrigenId").HasPrincipalKey("ProductoVarianteId", "Id")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_CapasCosto_CapaOrigen_MismaVariante");
                b.HasOne("Solqaryn.Domain.Entities.MovimientoInventario", null).WithMany()
                    .HasForeignKey("MovimientoInventarioOrigenId").OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_CapasCosto_MovimientoOrigen");
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", null).WithMany()
                    .HasForeignKey("ProductoVarianteId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_CapasCosto_ProductoVariantes");
                b.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", null).WithMany()
                    .HasForeignKey("AlmacenId", "UbicacionAlmacenId").HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_CapasCosto_Ubicacion_MismoAlmacen");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.AsignacionCostoMovimientoInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.CapaCostoInventario", null).WithMany()
                    .HasForeignKey("ProductoVarianteId", "CapaCostoInventarioId").HasPrincipalKey("ProductoVarianteId", "Id")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_AsignacionesCosto_Capa_MismaVariante");
                b.HasOne("Solqaryn.Domain.Entities.MovimientoInventario", null).WithMany()
                    .HasForeignKey("MovimientoInventarioId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_AsignacionesCosto_MovimientosInventario");
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", null).WithMany()
                    .HasForeignKey("ProductoVarianteId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_AsignacionesCosto_ProductoVariantes");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.VariacionCostoEstandarInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.CostoEstandarInventario", null).WithMany()
                    .HasForeignKey("ProductoVarianteId", "CostoEstandarInventarioId").HasPrincipalKey("ProductoVarianteId", "Id")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired().HasConstraintName("FK_VariacionesCostoEstandar_Version_MismaVariante");
                b.HasOne("Solqaryn.Domain.Entities.MovimientoInventario", null).WithMany()
                    .HasForeignKey("MovimientoInventarioId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_VariacionesCostoEstandar_MovimientosInventario");
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", null).WithMany()
                    .HasForeignKey("ProductoVarianteId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_VariacionesCostoEstandar_ProductoVariantes");
            });
        }
    }
}
