// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    partial class AppDbContextModelSnapshot
    {
        /// <summary>
        /// N7.6.C — overlay canónico del modelo persistente de configuración WhatsApp.
        /// Conserva el snapshot principal history-preserving y certifica el delta aditivo.
        /// </summary>
        private static void ApplyN76CModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.Entity("Solqaryn.Domain.Entities.ConfiguracionWhatsAppEmpresa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Activa")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true);

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<int>("EmpresaId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("NumeroTelefonoE164")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("varchar(16)");

                b.Property<string>("TokenSecretoReferencia")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("varchar(512)");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasDefaultValue(1L);

                b.Property<string>("WebhookSecretoReferencia")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("varchar(512)");

                b.HasKey("Id");

                b.HasIndex("EmpresaId")
                    .IsUnique()
                    .HasDatabaseName("UX_ConfiguracionesWhatsAppEmpresa_EmpresaId");

                b.ToTable("ConfiguracionesWhatsAppEmpresa", null, t =>
                {
                    t.HasCheckConstraint("CK_ConfiguracionesWhatsAppEmpresa_EmpresaId_Positivo", "`EmpresaId` > 0");
                    t.HasCheckConstraint("CK_ConfiguracionesWhatsAppEmpresa_Numero_E164", "`NumeroTelefonoE164` REGEXP '^\\+[0-9]{8,15}$'");
                    t.HasCheckConstraint("CK_ConfiguracionesWhatsAppEmpresa_Token_Referencia", "INSTR(`TokenSecretoReferencia`, '://') > 1");
                    t.HasCheckConstraint("CK_ConfiguracionesWhatsAppEmpresa_Version_Positiva", "`Version` > 0");
                    t.HasCheckConstraint("CK_ConfiguracionesWhatsAppEmpresa_Webhook_Referencia", "INSTR(`WebhookSecretoReferencia`, '://') > 1");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.ConfiguracionWhatsAppEmpresa", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Empresa", "Empresa")
                    .WithMany()
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Empresa");
            });
#pragma warning restore 612, 618
        }
    }
}
