// <auto-generated />
using Solqaryn.Domain.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart22(ModelBuilder modelBuilder)
        {
            var evaluacion = modelBuilder.Entity<EvaluacionProveedor>();

            evaluacion.ToTable("EvaluacionesProveedor", table =>
            {
                table.HasCheckConstraint("CK_EvaluacionesProveedor_ProveedorId_Valido", "`ProveedorId` > 0");
                table.HasCheckConstraint("CK_EvaluacionesProveedor_OrdenCompraId_Valido", "`OrdenCompraId` > 0");
                table.HasCheckConstraint("CK_EvaluacionesProveedor_RecepcionCompraId_Valido", "`RecepcionCompraId` > 0");
                table.HasCheckConstraint("CK_EvaluacionesProveedor_CantidadOrdenada_NoNegativa", "`CantidadOrdenada` >= 0");
                table.HasCheckConstraint("CK_EvaluacionesProveedor_CantidadAceptada_NoNegativa", "`CantidadAceptada` >= 0");
                table.HasCheckConstraint("CK_EvaluacionesProveedor_CantidadDanada_NoNegativa", "`CantidadDanada` >= 0");
                table.HasCheckConstraint("CK_EvaluacionesProveedor_CantidadSobrante_NoNegativa", "`CantidadSobrante` >= 0");
            });

            evaluacion.Property(x => x.Id).ValueGeneratedOnAdd();
            evaluacion.Property(x => x.CantidadOrdenada).HasPrecision(18, 4);
            evaluacion.Property(x => x.CantidadAceptada).HasPrecision(18, 4);
            evaluacion.Property(x => x.CantidadDanada).HasPrecision(18, 4);
            evaluacion.Property(x => x.CantidadSobrante).HasPrecision(18, 4);
            evaluacion.Property(x => x.CreadoPorNombreUsuario).HasMaxLength(150);
            evaluacion.Property(x => x.ActualizadoPorNombreUsuario).HasMaxLength(150);

            evaluacion.HasIndex(x => x.RecepcionCompraId)
                .HasDatabaseName("IX_EvaluacionesProveedor_RecepcionCompra");
            evaluacion.HasIndex(x => x.OrdenCompraId)
                .HasDatabaseName("IX_EvaluacionesProveedor_OrdenCompra");
            evaluacion.HasIndex(x => new { x.ProveedorId, x.FechaRecepcionUtc })
                .HasDatabaseName("IX_EvaluacionesProveedor_Proveedor_FechaRecepcion");

            evaluacion.HasOne("Solqaryn.Domain.Entities.Proveedor", null)
                .WithMany()
                .HasForeignKey("ProveedorId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_EvaluacionesProveedor_Proveedores_ProveedorId");
            evaluacion.HasOne("Solqaryn.Domain.Entities.OrdenCompra", null)
                .WithMany()
                .HasForeignKey("OrdenCompraId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_EvaluacionesProveedor_OrdenesCompra_OrdenCompraId");
            evaluacion.HasOne("Solqaryn.Domain.Entities.RecepcionCompra", null)
                .WithMany()
                .HasForeignKey("RecepcionCompraId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_EvaluacionesProveedor_RecepcionesCompra_RecepcionCompraId");
        }
    }
}
