// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart7(ModelBuilder modelBuilder)
        {
            // ERP-N1.5.C — correlación durable del Kardex. Este delta mantiene
            // el snapshot versionado alineado con MovimientoInventarioConfiguration
            // sin convertirlo en una proyección dinámica del modelo vigente.
            modelBuilder.Entity("Solqaryn.Domain.Entities.MovimientoInventario", b =>
            {
                b.Property<string>("CorrelationId")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)")
                    .HasDefaultValue("");

                b.HasIndex("CorrelationId", "Fecha")
                    .HasDatabaseName("IX_MovimientosInventario_CorrelationId_Fecha");
            });
        }
    }
}
