// <auto-generated />
using Solqaryn.Domain.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart24(ModelBuilder modelBuilder)
        {
            var pedido = modelBuilder.Entity<PedidoVenta>();

            pedido.ToTable("PedidosVenta", table =>
            {
                table.HasCheckConstraint("CK_PedidosVenta_Estado", "`Estado` IN (1, 2, 3)");
                table.HasCheckConstraint(
                    "CK_PedidosVenta_Idempotencia_Atomica",
                    "((`IdempotencyKey` IS NULL AND `IdempotencyFingerprint` IS NULL) OR (`IdempotencyKey` IS NOT NULL AND `IdempotencyFingerprint` IS NOT NULL))");
                table.HasCheckConstraint(
                    "CK_PedidosVenta_IdempotencyFingerprint_Sha256",
                    "(`IdempotencyFingerprint` IS NULL OR (CHAR_LENGTH(`IdempotencyFingerprint`) = 64 AND `IdempotencyFingerprint` REGEXP '^[0-9a-f]{64}$'))");
            });

            pedido.Property(x => x.Id).ValueGeneratedOnAdd();
            pedido.Property(x => x.Estado).HasConversion<int>().IsRequired();
            pedido.Property(x => x.ClienteNombreSnapshot).IsRequired().HasMaxLength(200);
            pedido.Property(x => x.ClienteDocumentoSnapshot).HasMaxLength(50);
            pedido.Property(x => x.Observaciones).HasMaxLength(1000);
            pedido.Property(x => x.IdempotencyKey).HasMaxLength(128);
            pedido.Property(x => x.IdempotencyFingerprint).HasMaxLength(64).IsFixedLength();
            pedido.Ignore(x => x.Total);
            pedido.Ignore(x => x.EsEditable);
            pedido.Ignore(x => x.EstaConfirmado);
            pedido.Ignore(x => x.EstaAnulado);

            pedido.HasIndex(x => x.CotizacionId)
                .IsUnique()
                .HasDatabaseName("UX_PedidosVenta_CotizacionId");
            pedido.HasIndex(x => x.IdempotencyKey)
                .IsUnique()
                .HasDatabaseName("UX_PedidosVenta_IdempotencyKey");
            pedido.HasIndex(x => new { x.ClienteId, x.Estado })
                .HasDatabaseName("IX_PedidosVenta_Cliente_Estado");

            pedido.HasOne(x => x.Cotizacion)
                .WithMany()
                .HasForeignKey(x => x.CotizacionId)
                .OnDelete(DeleteBehavior.Restrict);
            pedido.HasOne("Solqaryn.Domain.Entities.Cliente", null)
                .WithMany()
                .HasForeignKey("ClienteId")
                .OnDelete(DeleteBehavior.Restrict);
            pedido.HasMany(x => x.Detalles)
                .WithOne(x => x.PedidoVenta)
                .HasForeignKey(x => x.PedidoVentaId)
                .OnDelete(DeleteBehavior.Cascade);

            var detalle = modelBuilder.Entity<PedidoVentaDetalle>();

            detalle.ToTable("PedidoVentaDetalles", table =>
            {
                table.HasCheckConstraint("CK_PedidoVentaDetalles_Cantidad_Positiva", "`Cantidad` > 0");
                table.HasCheckConstraint("CK_PedidoVentaDetalles_PrecioUnitario_NoNegativo", "`PrecioUnitario` >= 0");
            });

            detalle.Property(x => x.Id).ValueGeneratedOnAdd();
            detalle.Property(x => x.Cantidad).HasPrecision(18, 4);
            detalle.Property(x => x.PrecioUnitario).HasPrecision(18, 4);
            detalle.Property(x => x.ProductoSkuSnapshot).HasMaxLength(80);
            detalle.Property(x => x.ProductoNombreSnapshot).HasMaxLength(150);
            detalle.Property(x => x.ProductoMarcaSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoModeloSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoColorSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoTallaSnapshot).HasMaxLength(100);
            detalle.Ignore(x => x.Total);

            detalle.HasIndex(x => x.PedidoVentaId)
                .HasDatabaseName("IX_PedidoVentaDetalles_PedidoVentaId");
            detalle.HasIndex(x => x.ProductoId)
                .HasDatabaseName("IX_PedidoVentaDetalles_ProductoId");
            detalle.HasIndex(x => x.ProductoVarianteId)
                .HasDatabaseName("IX_PedidoVentaDetalles_ProductoVarianteId");

            detalle.HasOne("Solqaryn.Domain.Entities.Producto", null)
                .WithMany()
                .HasForeignKey("ProductoId")
                .OnDelete(DeleteBehavior.Restrict);
            detalle.HasOne("Solqaryn.Domain.Entities.ProductoVariante", null)
                .WithMany()
                .HasForeignKey("ProductoVarianteId")
                .OnDelete(DeleteBehavior.Restrict);
        }
    }
}
