// <auto-generated />
using Solqaryn.Domain.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart26(ModelBuilder modelBuilder)
        {
            var devolucion = modelBuilder.Entity<DevolucionCliente>();
            devolucion.ToTable("DevolucionesCliente", table =>
            {
                table.HasCheckConstraint("CK_DevolucionesCliente_VentaId", "`VentaId` > 0");
                table.HasCheckConstraint("CK_DevolucionesCliente_FacturaId", "`FacturaId` IS NULL OR `FacturaId` > 0");
                table.HasCheckConstraint("CK_DevolucionesCliente_Estado", "`Estado` IN (1, 2, 3)");
                table.HasCheckConstraint("CK_DevolucionesCliente_IdempotenciaAtomica", "(`IdempotencyKey` IS NULL AND `IdempotencyFingerprint` IS NULL) OR (`IdempotencyKey` IS NOT NULL AND `IdempotencyFingerprint` IS NOT NULL)");
            });
            devolucion.Property(x => x.Estado).HasConversion<int>().IsRequired();
            devolucion.Property(x => x.Observaciones).HasMaxLength(1000);
            devolucion.Property(x => x.IdempotencyKey).HasMaxLength(128);
            devolucion.Property(x => x.IdempotencyFingerprint).HasColumnType("char(64)").HasMaxLength(64);
            devolucion.Property(x => x.MotivoAnulacion).HasMaxLength(1000);
            devolucion.HasIndex(x => x.VentaId).HasDatabaseName("IX_DevolucionesCliente_VentaId");
            devolucion.HasIndex(x => x.FacturaId).HasDatabaseName("IX_DevolucionesCliente_FacturaId");
            devolucion.HasIndex(x => x.Estado).HasDatabaseName("IX_DevolucionesCliente_Estado");
            devolucion.HasIndex(x => x.IdempotencyKey).IsUnique().HasDatabaseName("UX_DevolucionesCliente_IdempotencyKey");

            // Venta is a historical shared-type identity in this snapshot baseline.
            // Preserve the FK by entity-type name instead of coercing the relation to the modern CLR type.
            ((Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder)devolucion)
                .HasOne("Solqaryn.Domain.Entities.Venta", null).WithMany()
                .HasForeignKey("VentaId").OnDelete(DeleteBehavior.Restrict);

            // Factura is also a historical shared-type identity in this snapshot baseline.
            // Preserve the nullable FK by entity-type name instead of coercing the relation to the modern CLR type.
            ((Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder)devolucion)
                .HasOne("Solqaryn.Domain.Entities.Factura", null).WithMany()
                .HasForeignKey("FacturaId").OnDelete(DeleteBehavior.Restrict);
            devolucion.HasMany(x => x.Detalles).WithOne(x => x.DevolucionCliente).HasForeignKey(x => x.DevolucionClienteId).OnDelete(DeleteBehavior.Cascade);

            var detalle = modelBuilder.Entity<DevolucionClienteDetalle>();
            detalle.ToTable("DevolucionClienteDetalles", table =>
            {
                table.HasCheckConstraint("CK_DevolucionClienteDetalles_VentaDetalleId", "`VentaDetalleId` > 0");
                table.HasCheckConstraint("CK_DevolucionClienteDetalles_ProductoId", "`ProductoId` > 0");
                table.HasCheckConstraint("CK_DevolucionClienteDetalles_ProductoVarianteId", "`ProductoVarianteId` IS NULL OR `ProductoVarianteId` > 0");
                table.HasCheckConstraint("CK_DevolucionClienteDetalles_Cantidades", "`Cantidad` > 0 AND `CantidadVendidaSnapshot` > 0 AND `Cantidad` <= `CantidadVendidaSnapshot`");
                table.HasCheckConstraint("CK_DevolucionClienteDetalles_Precio", "`PrecioUnitarioSnapshot` >= 0");
                table.HasCheckConstraint("CK_DevolucionClienteDetalles_Resolucion", "`Resolucion` IN (1, 2, 3)");
            });
            detalle.Property(x => x.ProductoSkuSnapshot).HasMaxLength(120);
            detalle.Property(x => x.ProductoNombreSnapshot).HasMaxLength(200);
            detalle.Property(x => x.ProductoMarcaSnapshot).HasMaxLength(150);
            detalle.Property(x => x.ProductoModeloSnapshot).HasMaxLength(150);
            detalle.Property(x => x.ProductoColorSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoTallaSnapshot).HasMaxLength(100);
            detalle.Property(x => x.PrecioUnitarioSnapshot).HasColumnType("decimal(18,2)");
            detalle.Property(x => x.Resolucion).HasConversion<int>().IsRequired();
            detalle.HasIndex(x => new { x.DevolucionClienteId, x.VentaDetalleId }).IsUnique().HasDatabaseName("UX_DevolucionClienteDetalles_LineaVenta");
            detalle.HasIndex(x => x.VentaDetalleId).HasDatabaseName("IX_DevolucionClienteDetalles_VentaDetalleId");

            // VentaDetalle is a historical shared-type identity in this snapshot baseline.
            // Preserve the FK by entity-type name instead of coercing the relation to the modern CLR type.
            ((Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder)detalle)
                .HasOne("Solqaryn.Domain.Entities.VentaDetalle", null).WithMany()
                .HasForeignKey("VentaDetalleId").OnDelete(DeleteBehavior.Restrict);
        }
    }
}
