// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart2(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity("Solqaryn.Domain.Entities.AjusteInventarioDetalle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("AjusteInventarioId")
                    .HasColumnType("int");

                b.Property<int?>("CantidadAnteriorSnapshot")
                    .HasColumnType("int");

                b.Property<int?>("CantidadNuevaSnapshot")
                    .HasColumnType("int");

                b.Property<int>("CantidadObjetivo")
                    .HasColumnType("int");

                b.Property<string>("ColorSnapshot")
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<decimal?>("CostoUnitarioSnapshot")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("MarcaSnapshot")
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("ModeloSnapshot")
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("NombreSnapshot")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int>("ProductoId")
                    .HasColumnType("int");

                b.Property<int?>("ProductoVarianteId")
                    .HasColumnType("int");

                b.Property<string>("SkuSnapshot")
                    .HasMaxLength(80)
                    .HasColumnType("varchar(80)");

                b.Property<string>("TallaSnapshot")
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.HasKey("Id");

                b.HasIndex("AjusteInventarioId")
                    .HasDatabaseName("IX_AjusteInventarioDetalles_AjusteInventarioId");

                b.HasIndex("ProductoId", "ProductoVarianteId")
                    .HasDatabaseName("IX_AjusteInventarioDetalles_Producto_Variante");

                b.HasIndex("ProductoVarianteId");

                b.ToTable("AjusteInventarioDetalles", (string)null);
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.Sucursal", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<bool>("Activa")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true);

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("varchar(40)");

                b.Property<string>("CodigoActivoUnico")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)")
                    .HasComputedColumnSql("IF(Eliminado = 0, CONCAT(IF(EmpresaId IS NULL, 'LEGACY', CONCAT('E:', EmpresaId)), ':', UPPER(TRIM(Codigo))), NULL)", true);

                b.Property<string>("Correo")
                    .HasMaxLength(254)
                    .HasColumnType("varchar(254)");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("Direccion")
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<bool>("Eliminado")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(false);

                b.Property<int?>("EliminadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<int?>("EmpresaId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("FechaEliminacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<string>("Telefono")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<string>("ZonaHoraria")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)")
                    .HasDefaultValue("America/Tegucigalpa");

                b.HasKey("Id");

                b.HasIndex("CodigoActivoUnico")
                    .IsUnique()
                    .HasDatabaseName("UX_Sucursales_Codigo_Activo");

                b.HasIndex("EmpresaId")
                    .HasDatabaseName("IX_Sucursales_EmpresaId");

                b.HasIndex("Activa", "Eliminado")
                    .HasDatabaseName("IX_Sucursales_Estado");

                b.ToTable("Sucursales", (string)null);
            });
        }
    }
}
