// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart15(ModelBuilder modelBuilder)
        {
            // ERP-N2.3.C — recepción de mercancía documental y clave física destino.
            // Snapshot congelado: la materialización de stock/Kardex/costeo pertenece a N2.3.D.
            modelBuilder.Entity("Solqaryn.Domain.Entities.RecepcionCompra", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int?>("AnuladaPorUsuarioId").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<int>("Estado").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaAnulacionUtc").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaRecepcionUtc").HasColumnType("datetime(6)");
                b.Property<string>("IdempotencyFingerprint").HasMaxLength(64).HasColumnType("varchar(64)");
                b.Property<string>("IdempotencyKey").HasMaxLength(128).HasColumnType("varchar(128)");
                b.Property<string>("MotivoAnulacion").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("NumeroRecepcion").IsRequired().HasMaxLength(40).HasColumnType("varchar(40)");
                b.Property<string>("Observaciones").HasMaxLength(1000).HasColumnType("varchar(1000)");
                b.Property<int>("OrdenCompraId").HasColumnType("int");
                b.Property<string>("RecibidaPorNombreSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("RecibidaPorUsuarioId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("FechaRecepcionUtc").HasDatabaseName("IX_RecepcionesCompra_FechaRecepcionUtc");
                b.HasIndex("IdempotencyKey").IsUnique().HasDatabaseName("UX_RecepcionesCompra_IdempotencyKey");
                b.HasIndex("NumeroRecepcion").IsUnique().HasDatabaseName("UX_RecepcionesCompra_NumeroRecepcion");
                b.HasIndex("OrdenCompraId", "Estado").HasDatabaseName("IX_RecepcionesCompra_OrdenCompra_Estado");
                b.ToTable("RecepcionesCompra", t =>
                {
                    t.HasCheckConstraint(
                        "CK_RecepcionesCompra_IdempotenciaAtomica",
                        "(IdempotencyKey IS NULL AND IdempotencyFingerprint IS NULL) OR (IdempotencyKey IS NOT NULL AND CHAR_LENGTH(TRIM(IdempotencyKey)) > 0 AND IdempotencyFingerprint IS NOT NULL AND CHAR_LENGTH(IdempotencyFingerprint) = 64)");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.RecepcionCompraDetalle", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int>("AlmacenId").HasColumnType("int");
                b.Property<decimal>("CantidadDanada").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<decimal>("CantidadFaltante").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<decimal>("CantidadRecibida").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<decimal>("CantidadSobrante").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<decimal>("CostoUnitarioSnapshot").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<int>("OrdenCompraDetalleId").HasColumnType("int");
                b.Property<string>("ProductoColorSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("ProductoId").HasColumnType("int");
                b.Property<string>("ProductoMarcaSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoModeloSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoNombreSnapshot").HasMaxLength(250).HasColumnType("varchar(250)");
                b.Property<string>("ProductoSkuSnapshot").HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<string>("ProductoTallaSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int?>("ProductoVarianteId").HasColumnType("int");
                b.Property<int>("RecepcionCompraId").HasColumnType("int");
                b.Property<int?>("UbicacionAlmacenId").HasColumnType("int");
                b.Property<int>("UbicacionAlmacenIdUnica").ValueGeneratedOnAddOrUpdate().HasColumnType("int")
                    .HasComputedColumnSql("IFNULL(UbicacionAlmacenId, 0)", true);

                b.HasKey("Id");
                b.HasIndex("AlmacenId").HasDatabaseName("IX_RecepcionCompraDetalles_AlmacenId");
                b.HasIndex("AlmacenId", "UbicacionAlmacenId");
                b.HasIndex("OrdenCompraDetalleId").HasDatabaseName("IX_RecepcionCompraDetalles_OrdenCompraDetalleId");
                b.HasIndex("ProductoVarianteId");
                b.HasIndex("ProductoId", "ProductoVarianteId").HasDatabaseName("IX_RecepcionCompraDetalles_Producto_Variante");
                b.HasIndex("RecepcionCompraId", "OrdenCompraDetalleId", "AlmacenId", "UbicacionAlmacenIdUnica")
                    .IsUnique().HasDatabaseName("UX_RecepcionCompraDetalles_Recepcion_Linea_Almacen_Ubicacion");
                b.ToTable("RecepcionCompraDetalles", t =>
                {
                    t.HasCheckConstraint("CK_RecepcionCompraDetalles_ActividadFisica", "CantidadRecibida > 0 OR CantidadFaltante > 0");
                    t.HasCheckConstraint("CK_RecepcionCompraDetalles_BalanceFisico", "CantidadDanada + CantidadSobrante <= CantidadRecibida");
                    t.HasCheckConstraint("CK_RecepcionCompraDetalles_CantidadesNoNegativas", "CantidadRecibida >= 0 AND CantidadDanada >= 0 AND CantidadFaltante >= 0 AND CantidadSobrante >= 0");
                    t.HasCheckConstraint("CK_RecepcionCompraDetalles_CostoNoNegativo", "CostoUnitarioSnapshot >= 0");
                });
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.RecepcionCompra", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.OrdenCompra", "OrdenCompra").WithMany()
                    .HasForeignKey("OrdenCompraId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_RecepcionesCompra_OrdenesCompra_OrdenCompraId");
                b.Navigation("OrdenCompra");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.RecepcionCompraDetalle", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Almacen", "Almacen").WithMany().HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired().HasConstraintName("FK_RecepcionCompraDetalles_Almacenes_AlmacenId");
                b.HasOne("Solqaryn.Domain.Entities.OrdenCompraDetalle", "OrdenCompraDetalle").WithMany().HasForeignKey("OrdenCompraDetalleId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired().HasConstraintName("FK_RecepcionCompraDetalles_OrdenCompraDetalles_OrdenCompraDetalleId");
                b.HasOne("Solqaryn.Domain.Entities.Producto", "Producto").WithMany().HasForeignKey("ProductoId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired().HasConstraintName("FK_RecepcionCompraDetalles_Productos_ProductoId");
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", "ProductoVariante").WithMany().HasForeignKey("ProductoVarianteId")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_RecepcionCompraDetalles_ProductoVariantes_ProductoVarianteId");
                b.HasOne("Solqaryn.Domain.Entities.RecepcionCompra", "RecepcionCompra").WithMany("Detalles").HasForeignKey("RecepcionCompraId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired().HasConstraintName("FK_RecepcionCompraDetalles_RecepcionesCompra_RecepcionCompraId");
                b.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", "UbicacionAlmacen").WithMany()
                    .HasForeignKey("AlmacenId", "UbicacionAlmacenId").HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_RecepcionCompraDetalles_Ubicacion_MismoAlmacen");
                b.Navigation("Almacen");
                b.Navigation("OrdenCompraDetalle");
                b.Navigation("Producto");
                b.Navigation("ProductoVariante");
                b.Navigation("RecepcionCompra");
                b.Navigation("UbicacionAlmacen");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.RecepcionCompra", b => b.Navigation("Detalles"));
        }
    }
}
