// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart6(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity("Solqaryn.Domain.Entities.VentaDetalle", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Almacen", "Almacen")
                    .WithMany().HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_VentaDetalles_Almacenes_AlmacenId_N14");
                b.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", "UbicacionAlmacen")
                    .WithMany().HasForeignKey("AlmacenId", "UbicacionAlmacenId")
                    .HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_VentaDetalles_Ubicacion_MismoAlmacen_N14");
                b.Navigation("Almacen");
                b.Navigation("UbicacionAlmacen");
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.ConsumoInsumoDetalle", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Almacen", "Almacen")
                    .WithMany().HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_ConsumoInsumoDetalles_Almacenes_AlmacenId_N14");
                b.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", "UbicacionAlmacen")
                    .WithMany().HasForeignKey("AlmacenId", "UbicacionAlmacenId")
                    .HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_ConsumoInsumoDetalles_Ubicacion_MismoAlmacen_N14");
                b.Navigation("Almacen");
                b.Navigation("UbicacionAlmacen");
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.MovimientoInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Almacen", "Almacen")
                    .WithMany().HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovimientosInventario_Almacenes_AlmacenId_N14");
                b.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", "UbicacionAlmacen")
                    .WithMany().HasForeignKey("AlmacenId", "UbicacionAlmacenId")
                    .HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovimientosInventario_Ubicacion_MismoAlmacen_N14");
                b.Navigation("Almacen");
                b.Navigation("UbicacionAlmacen");
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.AjusteInventarioDetalle", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Almacen", "Almacen")
                    .WithMany().HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_AjusteInventarioDetalles_Almacenes_AlmacenId_N14");
                b.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", "UbicacionAlmacen")
                    .WithMany().HasForeignKey("AlmacenId", "UbicacionAlmacenId")
                    .HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_AjusteInventarioDetalles_Ubicacion_MismoAlmacen_N14");
                b.Navigation("Almacen");
                b.Navigation("UbicacionAlmacen");
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.AjusteInventario", b =>
            {
                b.Navigation("Detalles");
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.UbicacionAlmacen", b =>
            {
                b.Navigation("Hijas");
            });
        }
    }
}
