// <auto-generated />
using Solqaryn.Domain.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart27(ModelBuilder modelBuilder)
        {
            var nota = modelBuilder.Entity<NotaCreditoCliente>();
            nota.ToTable("NotasCreditoCliente", table =>
            {
                table.HasCheckConstraint("CK_NotasCreditoCliente_FacturaId", "`FacturaId` > 0");
                table.HasCheckConstraint("CK_NotasCreditoCliente_VentaId", "`VentaId` > 0");
                table.HasCheckConstraint("CK_NotasCreditoCliente_Moneda", "CHAR_LENGTH(`Moneda`) = 3");
                table.HasCheckConstraint("CK_NotasCreditoCliente_MontoCredito", "`MontoCredito` > 0");
            });
            nota.Property(x => x.Moneda).IsRequired().HasMaxLength(3);
            nota.Property(x => x.MontoCredito).HasColumnType("decimal(18,4)").IsRequired();
            nota.Property(x => x.Motivo).IsRequired().HasMaxLength(500);
            nota.Property(x => x.Observaciones).HasMaxLength(1000);
            nota.HasIndex(x => x.FacturaId).HasDatabaseName("IX_NotasCreditoCliente_FacturaId");
            nota.HasIndex(x => x.VentaId).HasDatabaseName("IX_NotasCreditoCliente_VentaId");

            // Factura is a historical shared-type identity in this snapshot baseline.
            // Preserve the FK by entity-type name instead of coercing the relation to the modern CLR type.
            ((Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder)nota)
                .HasOne("Solqaryn.Domain.Entities.Factura", null).WithMany()
                .HasForeignKey("FacturaId").OnDelete(DeleteBehavior.Restrict);
        }
    }
}
