// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart1(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity("Solqaryn.Domain.Entities.Factura", b =>
            {
                b.Property<string>("MetodoPagoCodigoSnapshot").HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("MetodoPagoNombreSnapshot").HasMaxLength(120).HasColumnType("varchar(120)");
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.FacturaPago", b =>
            {
                b.Property<string>("MetodoPagoCodigoSnapshot").HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("MetodoPagoNombreSnapshot").HasMaxLength(120).HasColumnType("varchar(120)");
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.Compra", b =>
            {
                b.Property<int?>("MetodoPagoId").HasColumnType("int");
                b.HasIndex("MetodoPagoId").HasDatabaseName("IX_Compras_MetodoPagoId");
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.MovimientoInventario", b =>
            {
                b.Property<int?>("CompraId").HasColumnType("int");
                b.Property<int?>("VentaId").HasColumnType("int");
                b.Property<int?>("ConsumoInsumoId").HasColumnType("int");
                b.Property<int?>("AjusteInventarioId").HasColumnType("int");
                b.Property<int?>("TransferenciaInventarioId").HasColumnType("int");
                b.Property<int?>("RecepcionCompraId").HasColumnType("int");
                b.HasIndex("CompraId").HasDatabaseName("IX_MovimientosInventario_CompraId");
                b.HasIndex("VentaId").HasDatabaseName("IX_MovimientosInventario_VentaId");
                b.HasIndex("ConsumoInsumoId").HasDatabaseName("IX_MovimientosInventario_ConsumoInsumoId");
                b.HasIndex("AjusteInventarioId").HasDatabaseName("IX_MovimientosInventario_AjusteInventarioId");
                b.HasIndex("TransferenciaInventarioId").HasDatabaseName("IX_MovimientosInventario_TransferenciaInventarioId");
                b.HasIndex("TransferenciaInventarioId", "Fecha").HasDatabaseName("IX_MovInv_Transferencia_Fecha_N16");
                b.HasIndex("RecepcionCompraId").HasDatabaseName("IX_MovimientosInventario_RecepcionCompraId");
                b.HasIndex("RecepcionCompraId", "Fecha").HasDatabaseName("IX_MovInv_RecepcionCompra_Fecha_N23");
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.AjusteInventario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<string>("AnuladoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("AnuladoPorUsuarioId").HasColumnType("int");
                b.Property<string>("ConfirmadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ConfirmadoPorUsuarioId").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<string>("Estado").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaAnulacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaAjuste").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaConfirmacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<string>("Motivo").IsRequired().HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("MotivoAnulacion").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("NumeroAjuste").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<string>("Observaciones").HasMaxLength(1000).HasColumnType("varchar(1000)");
                b.HasKey("Id");
                b.HasIndex("Estado", "FechaAjuste").HasDatabaseName("IX_AjustesInventario_Estado_Fecha");
                b.HasIndex("NumeroAjuste").IsUnique().HasDatabaseName("UX_AjustesInventario_Numero");
                b.ToTable("AjustesInventario", (string)null);
            });
        }
    }
}