// <auto-generated />
using Solqaryn.Domain.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart21(ModelBuilder modelBuilder)
        {
            var cuenta = modelBuilder.Entity<CuentaPorPagar>();

            cuenta.ToTable("CuentasPorPagar", table =>
            {
                table.HasCheckConstraint("CK_CuentasPorPagar_IdsValidos",
                    "FacturaProveedorId > 0 AND ProveedorId > 0");
                table.HasCheckConstraint("CK_CuentasPorPagar_CondicionPagoValida",
                    "CondicionPago IN (1, 2)");
                table.HasCheckConstraint("CK_CuentasPorPagar_EstadoValido",
                    "Estado IN (1, 2, 3, 4)");
                table.HasCheckConstraint("CK_CuentasPorPagar_MonedaIso3",
                    "CHAR_LENGTH(TRIM(Moneda)) = 3");
                table.HasCheckConstraint("CK_CuentasPorPagar_MontoOriginalPositivo",
                    "MontoOriginal > 0");
                table.HasCheckConstraint("CK_CuentasPorPagar_FechasValidas",
                    "FechaVencimientoUtc >= FechaEmisionUtc");
                table.HasCheckConstraint("CK_CuentasPorPagar_ContadoVenceEmision",
                    "CondicionPago <> 1 OR FechaVencimientoUtc = FechaEmisionUtc");
                table.HasCheckConstraint("CK_CuentasPorPagar_CreditoVenceDespues",
                    "CondicionPago <> 2 OR FechaVencimientoUtc > FechaEmisionUtc");
            });

            cuenta.Property(x => x.Id).ValueGeneratedOnAdd();
            cuenta.Property(x => x.Moneda).HasMaxLength(3).IsRequired();
            cuenta.Property(x => x.CondicionPago).HasConversion<int>().IsRequired();
            cuenta.Property(x => x.Estado).HasConversion<int>().IsRequired();
            cuenta.Property(x => x.MontoOriginal).HasPrecision(18, 4).IsRequired();
            cuenta.Property(x => x.MotivoAnulacion).HasMaxLength(500);
            cuenta.Property(x => x.CreadoPorNombreUsuario).HasMaxLength(150);
            cuenta.Property(x => x.ActualizadoPorNombreUsuario).HasMaxLength(150);

            cuenta.Ignore(x => x.MontoAplicado);
            cuenta.Ignore(x => x.Saldo);

            cuenta.HasIndex(x => x.FacturaProveedorId)
                .IsUnique()
                .HasDatabaseName("UX_CuentasPorPagar_FacturaProveedorId");
            cuenta.HasIndex(x => new { x.ProveedorId, x.Estado, x.FechaVencimientoUtc })
                .HasDatabaseName("IX_CuentasPorPagar_Proveedor_Estado_Vencimiento");
            cuenta.HasIndex(x => new { x.Estado, x.FechaVencimientoUtc })
                .HasDatabaseName("IX_CuentasPorPagar_Estado_Vencimiento");

            cuenta.HasOne("Solqaryn.Domain.Entities.FacturaProveedor", null)
                .WithMany()
                .HasForeignKey("FacturaProveedorId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_CuentasPorPagar_FacturasProveedor_FacturaProveedorId");
            cuenta.HasOne("Solqaryn.Domain.Entities.Proveedor", null)
                .WithMany()
                .HasForeignKey("ProveedorId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_CuentasPorPagar_Proveedores_ProveedorId");
            cuenta.HasMany(x => x.Aplicaciones)
                .WithOne()
                .HasForeignKey(x => x.CuentaPorPagarId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_AplicacionesCuentaPorPagar_CuentasPorPagar_CuentaPorPagarId");

            var aplicacion = modelBuilder.Entity<AplicacionCuentaPorPagar>();

            aplicacion.ToTable("AplicacionesCuentaPorPagar", table =>
            {
                table.HasCheckConstraint("CK_AplicacionesCuentaPorPagar_CuentaValida",
                    "CuentaPorPagarId > 0");
                table.HasCheckConstraint("CK_AplicacionesCuentaPorPagar_TipoValido",
                    "Tipo IN (1, 2, 3, 4)");
                table.HasCheckConstraint("CK_AplicacionesCuentaPorPagar_MontoPositivo",
                    "Monto > 0");
            });

            aplicacion.Property(x => x.Id).ValueGeneratedOnAdd();
            aplicacion.Property(x => x.Tipo).HasConversion<int>().IsRequired();
            aplicacion.Property(x => x.Monto).HasPrecision(18, 4).IsRequired();
            aplicacion.Property(x => x.IdempotencyKey).HasMaxLength(128).IsRequired();
            aplicacion.Property(x => x.ReferenciaExterna).HasMaxLength(150);
            aplicacion.Property(x => x.MotivoReversion).HasMaxLength(500);
            aplicacion.Property(x => x.CreadoPorNombreUsuario).HasMaxLength(150);
            aplicacion.Property(x => x.ActualizadoPorNombreUsuario).HasMaxLength(150);

            aplicacion.HasIndex(x => new { x.CuentaPorPagarId, x.IdempotencyKey })
                .IsUnique()
                .HasDatabaseName("UX_AplicacionesCuentaPorPagar_Cuenta_IdempotencyKey");
            aplicacion.HasIndex(x => new { x.CuentaPorPagarId, x.FechaAplicacionUtc })
                .HasDatabaseName("IX_AplicacionesCuentaPorPagar_Cuenta_Fecha");
            aplicacion.HasIndex(x => new { x.Tipo, x.FechaAplicacionUtc })
                .HasDatabaseName("IX_AplicacionesCuentaPorPagar_Tipo_Fecha");
        }
    }
}
