// <auto-generated />
using Solqaryn.Domain.Entities;
using Solqaryn.Domain.Entities.Cajas;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart29(ModelBuilder modelBuilder)
        {
            var caja = modelBuilder.Entity<Caja>();
            caja.ToTable("Cajas", table =>
            {
                table.HasCheckConstraint("CK_Cajas_Estado", "`Estado` IN (1, 2)");
                table.HasCheckConstraint("CK_Cajas_SesionActivaId", "`SesionActivaId` IS NULL OR `SesionActivaId` > 0");
            });
            caja.Property(x => x.Nombre).IsRequired().HasMaxLength(150);
            caja.Property(x => x.Estado).IsRequired();
            caja.HasIndex(x => x.Estado).HasDatabaseName("IX_Cajas_Estado");
            caja.HasIndex(x => x.SesionActivaId).IsUnique().HasDatabaseName("UX_Cajas_SesionActivaId");
            caja.HasOne<CajaSesion>().WithMany().HasForeignKey(x => x.SesionActivaId).OnDelete(DeleteBehavior.Restrict);

            var sesion = modelBuilder.Entity<CajaSesion>();
            sesion.ToTable("CajaSesiones", table =>
            {
                table.HasCheckConstraint("CK_CajaSesiones_CajaId", "`CajaId` > 0");
                table.HasCheckConstraint("CK_CajaSesiones_UsuarioId", "`UsuarioId` > 0");
                table.HasCheckConstraint("CK_CajaSesiones_Estado", "`Estado` IN (1, 2, 3, 4)");
                table.HasCheckConstraint("CK_CajaSesiones_FondoInicial", "`FondoInicial` >= 0");
                table.HasCheckConstraint("CK_CajaSesiones_TotalIngresos", "`TotalIngresos` >= 0");
                table.HasCheckConstraint("CK_CajaSesiones_TotalRetiros", "`TotalRetiros` >= 0");
                table.HasCheckConstraint("CK_CajaSesiones_TotalDepositos", "`TotalDepositos` >= 0");
                table.HasCheckConstraint("CK_CajaSesiones_SaldoContado", "`SaldoContado` IS NULL OR `SaldoContado` >= 0");
                table.HasCheckConstraint("CK_CajaSesiones_FechaCierre", "(`Estado` = 4 AND `FechaCierre` IS NOT NULL) OR (`Estado` <> 4 AND `FechaCierre` IS NULL)");
            });
            sesion.Property(x => x.FondoInicial).HasColumnType("decimal(18,4)").IsRequired();
            sesion.Property(x => x.TotalIngresos).HasColumnType("decimal(18,4)").IsRequired();
            sesion.Property(x => x.TotalRetiros).HasColumnType("decimal(18,4)").IsRequired();
            sesion.Property(x => x.TotalDepositos).HasColumnType("decimal(18,4)").IsRequired();
            sesion.Property(x => x.SaldoEsperado).HasColumnType("decimal(18,4)");
            sesion.Property(x => x.SaldoContado).HasColumnType("decimal(18,4)");
            sesion.Property(x => x.Diferencia).HasColumnType("decimal(18,4)");
            sesion.Property(x => x.FechaApertura).IsRequired();
            sesion.Property(x => x.Estado).IsRequired();
            sesion.HasIndex(x => x.CajaId).HasDatabaseName("IX_CajaSesiones_CajaId");
            sesion.HasIndex(x => x.UsuarioId).HasDatabaseName("IX_CajaSesiones_UsuarioId");
            sesion.HasIndex(x => new { x.CajaId, x.Estado }).HasDatabaseName("IX_CajaSesiones_CajaId_Estado");
            sesion.HasOne<Caja>().WithMany().HasForeignKey(x => x.CajaId).OnDelete(DeleteBehavior.Restrict);
            ((Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder)sesion)
                .HasOne("Solqaryn.Domain.Entities.Usuario", null).WithMany()
                .HasForeignKey("UsuarioId").OnDelete(DeleteBehavior.Restrict);
            sesion.HasMany(x => x.Movimientos).WithOne().HasForeignKey(x => x.CajaSesionId).OnDelete(DeleteBehavior.Cascade);
            sesion.Navigation(x => x.Movimientos).UsePropertyAccessMode(PropertyAccessMode.Field);

            var movimiento = modelBuilder.Entity<CajaMovimiento>();
            movimiento.ToTable("CajaMovimientos", table =>
            {
                table.HasCheckConstraint("CK_CajaMovimientos_CajaSesionId", "`CajaSesionId` > 0");
                table.HasCheckConstraint("CK_CajaMovimientos_UsuarioId", "`UsuarioId` > 0");
                table.HasCheckConstraint("CK_CajaMovimientos_Tipo", "`Tipo` IN (1, 2, 3, 4, 5)");
                table.HasCheckConstraint("CK_CajaMovimientos_Monto", "`Monto` > 0");
                table.HasCheckConstraint("CK_CajaMovimientos_Referencia", "CHAR_LENGTH(TRIM(`Referencia`)) > 0");
            });
            movimiento.Property(x => x.Tipo).IsRequired();
            movimiento.Property(x => x.Monto).HasColumnType("decimal(18,4)").IsRequired();
            movimiento.Property(x => x.Referencia).IsRequired();
            movimiento.Property(x => x.FechaOperacion).IsRequired();
            movimiento.HasIndex(x => new { x.CajaSesionId, x.FechaOperacion }).HasDatabaseName("IX_CajaMovimientos_Sesion_Fecha");
            movimiento.HasIndex(x => x.UsuarioId).HasDatabaseName("IX_CajaMovimientos_UsuarioId");
            movimiento.HasIndex(x => x.Tipo).HasDatabaseName("IX_CajaMovimientos_Tipo");
            ((Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder)movimiento)
                .HasOne("Solqaryn.Domain.Entities.Usuario", null).WithMany()
                .HasForeignKey("UsuarioId").OnDelete(DeleteBehavior.Restrict);
        }
    }
}
