// <auto-generated />
using Solqaryn.Domain.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart20(ModelBuilder modelBuilder)
        {
            var nota = modelBuilder.Entity<NotaCreditoProveedor>();

            nota.ToTable("NotasCreditoProveedor", table =>
            {
                table.HasCheckConstraint("CK_NotasCreditoProveedor_IdsValidos",
                    "ProveedorId > 0 AND FacturaProveedorId > 0 AND (DevolucionProveedorId IS NULL OR DevolucionProveedorId > 0)");
                table.HasCheckConstraint("CK_NotasCreditoProveedor_EstadoValido",
                    "Estado IN (1, 2, 3)");
                table.HasCheckConstraint("CK_NotasCreditoProveedor_MonedaIso3",
                    "CHAR_LENGTH(TRIM(Moneda)) = 3");
                table.HasCheckConstraint("CK_NotasCreditoProveedor_ImportesNoNegativos",
                    "SubtotalCredito >= 0 AND ImpuestoCredito >= 0 AND (SubtotalCredito + ImpuestoCredito) > 0");
            });

            nota.Property(x => x.Id).ValueGeneratedOnAdd();
            nota.Property(x => x.NumeroNotaCredito).HasMaxLength(80).IsRequired();
            nota.Property(x => x.ProveedorNombreSnapshot).HasMaxLength(250).IsRequired();
            nota.Property(x => x.Moneda).HasMaxLength(3).IsRequired();
            nota.Property(x => x.ReferenciaFiscal).HasMaxLength(120);
            nota.Property(x => x.Motivo).HasMaxLength(500).IsRequired();
            nota.Property(x => x.Observaciones).HasMaxLength(1000);
            nota.Property(x => x.SubtotalCredito).HasPrecision(18, 4).IsRequired();
            nota.Property(x => x.ImpuestoCredito).HasPrecision(18, 4).IsRequired();
            nota.Property(x => x.Estado).HasConversion<int>().IsRequired();
            nota.Property(x => x.RegistradaPorNombreSnapshot).HasMaxLength(150);
            nota.Property(x => x.MotivoAnulacion).HasMaxLength(500);
            nota.Property(x => x.CreadoPorNombreUsuario).HasMaxLength(150);
            nota.Property(x => x.ActualizadoPorNombreUsuario).HasMaxLength(150);

            nota.Ignore(x => x.TotalCredito);
            nota.Ignore(x => x.EsEditable);

            nota.HasIndex(x => new { x.ProveedorId, x.NumeroNotaCredito })
                .IsUnique()
                .HasDatabaseName("UX_NotasCreditoProveedor_Proveedor_Numero");
            nota.HasIndex(x => x.FacturaProveedorId)
                .HasDatabaseName("IX_NotasCreditoProveedor_FacturaProveedorId");
            nota.HasIndex(x => x.DevolucionProveedorId)
                .HasDatabaseName("IX_NotasCreditoProveedor_DevolucionProveedorId");
            nota.HasIndex(x => new { x.ProveedorId, x.Estado })
                .HasDatabaseName("IX_NotasCreditoProveedor_Proveedor_Estado");
            nota.HasIndex(x => x.FechaEmisionUtc)
                .HasDatabaseName("IX_NotasCreditoProveedor_FechaEmisionUtc");

            nota.HasOne("Solqaryn.Domain.Entities.Proveedor", null)
                .WithMany()
                .HasForeignKey("ProveedorId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_NotasCreditoProveedor_Proveedores_ProveedorId");
            nota.HasOne("Solqaryn.Domain.Entities.FacturaProveedor", null)
                .WithMany()
                .HasForeignKey("FacturaProveedorId")
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_NotasCreditoProveedor_FacturasProveedor_FacturaProveedorId");
            nota.HasOne<DevolucionProveedor>()
                .WithMany()
                .HasForeignKey(x => x.DevolucionProveedorId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_NotasCreditoProveedor_DevolucionesProveedor_DevolucionProveedorId");
        }
    }
}
