// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart9(ModelBuilder modelBuilder)
        {
            // ERP-N1.7.C — persistencia normalizada de conteos físicos.
            modelBuilder.Entity("Solqaryn.Domain.Entities.ConteoInventario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int>("AlmacenId").HasColumnType("int");
                b.Property<int?>("AprobadoPorUsuarioId").HasColumnType("int");
                b.Property<int?>("CanceladoPorUsuarioId").HasColumnType("int");
                b.Property<int?>("CategoriaId").HasColumnType("int");
                b.Property<int?>("CerradoPorUsuarioId").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<bool>("EsCiego").HasColumnType("tinyint(1)").HasDefaultValue(false);
                b.Property<int>("Estado").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaAprobacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaCancelacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaCierre").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaInicio").HasColumnType("datetime(6)");
                b.Property<int?>("IniciadoPorUsuarioId").HasColumnType("int");
                b.Property<string>("MotivoCancelacion").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("Numero").IsRequired().HasMaxLength(30).HasColumnType("varchar(30)");
                b.Property<string>("Observaciones").HasMaxLength(1000).HasColumnType("varchar(1000)");
                b.Property<int>("Tipo").HasColumnType("int");
                b.Property<int?>("UbicacionAlmacenId").HasColumnType("int");

                b.HasKey("Id");
                b.HasAlternateKey("Id", "AlmacenId").HasName("AK_ConteosInventario_Id_AlmacenId");
                b.HasIndex("AlmacenId", "Estado").HasDatabaseName("IX_ConteosInventario_Almacen_Estado");
                b.HasIndex("CategoriaId").HasDatabaseName("IX_ConteosInventario_CategoriaId");
                b.HasIndex("Numero").IsUnique().HasDatabaseName("UX_ConteosInventario_Numero");
                b.HasIndex("Tipo", "Estado").HasDatabaseName("IX_ConteosInventario_Tipo_Estado");
                b.HasIndex("UbicacionAlmacenId").HasDatabaseName("IX_ConteosInventario_UbicacionAlmacenId");
                b.HasIndex("AlmacenId", "UbicacionAlmacenId");
                b.ToTable("ConteosInventario");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.ConteoInventarioDetalle", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int?>("AjusteInventarioId").HasColumnType("int");
                b.Property<int>("AlmacenId").HasColumnType("int");
                b.Property<int?>("CantidadContada").HasColumnType("int");
                b.Property<int>("ConteoInventarioId").HasColumnType("int");
                b.Property<int?>("ContadoPorUsuarioId").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<int?>("Diferencia").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaConteo").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<string>("ProductoColorSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("ProductoMarcaSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoModeloSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoSkuSnapshot").HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<string>("ProductoTallaSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("ProductoVarianteId").HasColumnType("int");
                b.Property<bool>("SnapshotMaterializado").HasColumnType("tinyint(1)").HasDefaultValue(false);
                b.Property<int>("StockEsperadoSnapshot").HasColumnType("int");
                b.Property<int?>("UbicacionAlmacenId").HasColumnType("int");
                b.Property<int>("UbicacionNormalizada").ValueGeneratedOnAddOrUpdate().HasColumnType("int")
                    .HasComputedColumnSql("COALESCE(`UbicacionAlmacenId`, 0)", true);

                b.HasKey("Id");
                b.HasIndex("AjusteInventarioId").HasDatabaseName("IX_ConteoDetalles_AjusteInventarioId");
                b.HasIndex("AlmacenId", "UbicacionAlmacenId");
                b.HasIndex("ConteoInventarioId", "AlmacenId");
                b.HasIndex("ConteoInventarioId", "ProductoVarianteId", "AlmacenId", "UbicacionNormalizada")
                    .IsUnique().HasDatabaseName("UX_ConteoDetalles_ClaveFisica");
                b.HasIndex("ProductoVarianteId", "AlmacenId", "UbicacionAlmacenId")
                    .HasDatabaseName("IX_ConteoDetalles_ExistenciaFisica");
                b.ToTable("ConteoInventarioDetalles");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.ConteoInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Almacen", "Almacen").WithMany().HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired().HasConstraintName("FK_ConteosInventario_Almacenes_AlmacenId");
                b.HasOne("Solqaryn.Domain.Entities.Categoria", "Categoria").WithMany().HasForeignKey("CategoriaId")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_ConteosInventario_Categorias_CategoriaId");
                b.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", "UbicacionAlmacen").WithMany()
                    .HasForeignKey("AlmacenId", "UbicacionAlmacenId").HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_ConteosInventario_Ubicacion_MismoAlmacen");
                b.Navigation("Almacen");
                b.Navigation("Categoria");
                b.Navigation("UbicacionAlmacen");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.ConteoInventarioDetalle", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.AjusteInventario", "AjusteInventario").WithMany().HasForeignKey("AjusteInventarioId")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_ConteoDetalles_AjustesInventario_AjusteInventarioId");
                b.HasOne("Solqaryn.Domain.Entities.Almacen", "Almacen").WithMany().HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired().HasConstraintName("FK_ConteoDetalles_Almacenes_AlmacenId");
                b.HasOne("Solqaryn.Domain.Entities.ConteoInventario", "ConteoInventario").WithMany("Detalles")
                    .HasForeignKey("ConteoInventarioId", "AlmacenId").HasPrincipalKey("Id", "AlmacenId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired().HasConstraintName("FK_ConteoInventarioDetalles_Conteo_MismoAlmacen");
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", "ProductoVariante").WithMany().HasForeignKey("ProductoVarianteId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired().HasConstraintName("FK_ConteoDetalles_ProductoVariantes_ProductoVarianteId");
                b.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", "UbicacionAlmacen").WithMany()
                    .HasForeignKey("AlmacenId", "UbicacionAlmacenId").HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_ConteoDetalles_Ubicacion_MismoAlmacen");
                b.Navigation("AjusteInventario");
                b.Navigation("Almacen");
                b.Navigation("ConteoInventario");
                b.Navigation("ProductoVariante");
                b.Navigation("UbicacionAlmacen");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.ConteoInventario", b =>
            {
                b.Navigation("Detalles");
            });
        }
    }
}
