// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart14(ModelBuilder modelBuilder)
        {
            // ERP-N2.1 / N2.2 — solicitudes y órdenes de compra documentales.
            // Snapshot congelado: no enlaza configuraciones vivas para conservar detección de drift futura.
            modelBuilder.Entity("Solqaryn.Domain.Entities.SolicitudCompra", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<string>("DecididaPorNombreSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("DecididaPorUsuarioId").HasColumnType("int");
                b.Property<int>("Estado").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaDecisionUtc").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaSolicitudUtc").HasColumnType("datetime(6)");
                b.Property<string>("MotivoRechazo").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("Notas").HasMaxLength(1000).HasColumnType("varchar(1000)");
                b.Property<string>("NumeroSolicitud").IsRequired().HasMaxLength(40).HasColumnType("varchar(40)");
                b.Property<int?>("ProveedorId").HasColumnType("int");
                b.Property<string>("SolicitadaPorNombreSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("SolicitadaPorUsuarioId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("Estado", "FechaSolicitudUtc").HasDatabaseName("IX_SolicitudesCompra_Estado_FechaSolicitud");
                b.HasIndex("NumeroSolicitud").IsUnique().HasDatabaseName("UX_SolicitudesCompra_NumeroSolicitud");
                b.HasIndex("ProveedorId").HasDatabaseName("IX_SolicitudesCompra_ProveedorId");
                b.ToTable("SolicitudesCompra");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.SolicitudCompraDetalle", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<decimal>("CantidadSolicitada").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<decimal?>("CostoEstimadoUnitario").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<string>("Observacion").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("ProductoColorSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("ProductoId").HasColumnType("int");
                b.Property<string>("ProductoMarcaSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoModeloSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoNombreSnapshot").HasMaxLength(250).HasColumnType("varchar(250)");
                b.Property<string>("ProductoSkuSnapshot").HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<string>("ProductoTallaSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int?>("ProductoVarianteId").HasColumnType("int");
                b.Property<int>("SolicitudCompraId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("ProductoVarianteId");
                b.HasIndex("SolicitudCompraId").HasDatabaseName("IX_SolicitudCompraDetalles_SolicitudCompraId");
                b.HasIndex("ProductoId", "ProductoVarianteId").HasDatabaseName("IX_SolicitudCompraDetalles_Producto_Variante");
                b.ToTable("SolicitudCompraDetalles");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.OrdenCompra", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<string>("AprobadaPorNombreSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("AprobadaPorUsuarioId").HasColumnType("int");
                b.Property<int?>("CanceladaPorUsuarioId").HasColumnType("int");
                b.Property<string>("CondicionesCompra").HasMaxLength(1000).HasColumnType("varchar(1000)");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<int?>("EnviadaAprobacionPorUsuarioId").HasColumnType("int");
                b.Property<int>("Estado").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaAprobacionUtc").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaCancelacionUtc").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaEnvioAprobacionUtc").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaEsperadaUtc").HasColumnType("datetime(6)");
                b.Property<string>("IdempotencyFingerprint").HasMaxLength(64).HasColumnType("varchar(64)");
                b.Property<string>("IdempotencyKey").HasMaxLength(128).HasColumnType("varchar(128)");
                b.Property<string>("Moneda").IsRequired().HasMaxLength(3).HasColumnType("varchar(3)");
                b.Property<string>("MotivoCancelacion").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("NumeroOrden").IsRequired().HasMaxLength(40).HasColumnType("varchar(40)");
                b.Property<string>("Observaciones").HasMaxLength(1000).HasColumnType("varchar(1000)");
                b.Property<string>("ProveedorDocumentoSnapshot").HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<int>("ProveedorId").HasColumnType("int");
                b.Property<string>("ProveedorNombreSnapshot").IsRequired().HasMaxLength(250).HasColumnType("varchar(250)");
                b.Property<int?>("SolicitudCompraId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("Estado", "FechaEsperadaUtc").HasDatabaseName("IX_OrdenesCompra_Estado_FechaEsperada");
                b.HasIndex("IdempotencyKey").IsUnique().HasDatabaseName("UX_OrdenesCompra_IdempotencyKey");
                b.HasIndex("NumeroOrden").IsUnique().HasDatabaseName("UX_OrdenesCompra_NumeroOrden");
                b.HasIndex("ProveedorId").HasDatabaseName("IX_OrdenesCompra_ProveedorId");
                b.HasIndex("SolicitudCompraId").HasDatabaseName("IX_OrdenesCompra_SolicitudCompraId");
                b.ToTable("OrdenesCompra");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.OrdenCompraDetalle", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<decimal>("CantidadOrdenada").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<decimal>("Descuento").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<decimal>("Impuesto").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<string>("Observacion").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int>("OrdenCompraId").HasColumnType("int");
                b.Property<string>("ProductoColorSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("ProductoId").HasColumnType("int");
                b.Property<string>("ProductoMarcaSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoModeloSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoNombreSnapshot").HasMaxLength(250).HasColumnType("varchar(250)");
                b.Property<string>("ProductoSkuSnapshot").HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<string>("ProductoTallaSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int?>("ProductoVarianteId").HasColumnType("int");
                b.Property<decimal>("PrecioUnitario").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.HasKey("Id");
                b.HasIndex("OrdenCompraId").HasDatabaseName("IX_OrdenCompraDetalles_OrdenCompraId");
                b.HasIndex("ProductoVarianteId");
                b.HasIndex("ProductoId", "ProductoVarianteId").HasDatabaseName("IX_OrdenCompraDetalles_Producto_Variante");
                b.ToTable("OrdenCompraDetalles");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.SolicitudCompra", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Proveedor", "Proveedor").WithMany()
                    .HasForeignKey("ProveedorId").OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_SolicitudesCompra_Proveedores_ProveedorId");
                b.Navigation("Proveedor");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.SolicitudCompraDetalle", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Producto", "Producto").WithMany()
                    .HasForeignKey("ProductoId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_SolicitudCompraDetalles_Productos_ProductoId");
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", "ProductoVariante").WithMany()
                    .HasForeignKey("ProductoVarianteId").OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_SolicitudCompraDetalles_ProductoVariantes_ProductoVarianteId");
                b.HasOne("Solqaryn.Domain.Entities.SolicitudCompra", "SolicitudCompra").WithMany("Detalles")
                    .HasForeignKey("SolicitudCompraId").OnDelete(DeleteBehavior.Cascade).IsRequired()
                    .HasConstraintName("FK_SolicitudCompraDetalles_SolicitudesCompra_SolicitudCompraId");
                b.Navigation("Producto");
                b.Navigation("ProductoVariante");
                b.Navigation("SolicitudCompra");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.OrdenCompra", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Proveedor", "Proveedor").WithMany()
                    .HasForeignKey("ProveedorId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_OrdenesCompra_Proveedores_ProveedorId");
                b.HasOne("Solqaryn.Domain.Entities.SolicitudCompra", "SolicitudCompra").WithMany()
                    .HasForeignKey("SolicitudCompraId").OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_OrdenesCompra_SolicitudesCompra_SolicitudCompraId");
                b.Navigation("Proveedor");
                b.Navigation("SolicitudCompra");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.OrdenCompraDetalle", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.OrdenCompra", "OrdenCompra").WithMany("Detalles")
                    .HasForeignKey("OrdenCompraId").OnDelete(DeleteBehavior.Cascade).IsRequired()
                    .HasConstraintName("FK_OrdenCompraDetalles_OrdenesCompra_OrdenCompraId");
                b.HasOne("Solqaryn.Domain.Entities.Producto", "Producto").WithMany()
                    .HasForeignKey("ProductoId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                    .HasConstraintName("FK_OrdenCompraDetalles_Productos_ProductoId");
                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", "ProductoVariante").WithMany()
                    .HasForeignKey("ProductoVarianteId").OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_OrdenCompraDetalles_ProductoVariantes_ProductoVarianteId");
                b.Navigation("OrdenCompra");
                b.Navigation("Producto");
                b.Navigation("ProductoVariante");
            });

            modelBuilder.Entity("Solqaryn.Domain.Entities.SolicitudCompra", b => b.Navigation("Detalles"));
            modelBuilder.Entity("Solqaryn.Domain.Entities.OrdenCompra", b => b.Navigation("Detalles"));
        }
    }
}
