// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart5(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity("Solqaryn.Domain.Entities.MovimientoInventario", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Compra", null)
                    .WithMany()
                    .HasForeignKey("CompraId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovimientosInventario_Compras_CompraId_N06");

                b.HasOne("Solqaryn.Domain.Entities.Venta", null)
                    .WithMany()
                    .HasForeignKey("VentaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovimientosInventario_Ventas_VentaId_N06");

                b.HasOne("Solqaryn.Domain.Entities.ConsumoInsumo", null)
                    .WithMany()
                    .HasForeignKey("ConsumoInsumoId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovimientosInventario_ConsumosInsumos_ConsumoInsumoId_N06");

                b.HasOne("Solqaryn.Domain.Entities.AjusteInventario", null)
                    .WithMany()
                    .HasForeignKey("AjusteInventarioId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovInv_AjusteInventarioId_N07");

                b.HasOne("Solqaryn.Domain.Entities.TransferenciaInventario", null)
                    .WithMany()
                    .HasForeignKey("TransferenciaInventarioId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovInv_TransferenciaInventarioId_N16");
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.AjusteInventarioDetalle", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.AjusteInventario", "AjusteInventario")
                    .WithMany("Detalles")
                    .HasForeignKey("AjusteInventarioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_AjusteInventarioDetalles_AjustesInventario");

                b.HasOne("Solqaryn.Domain.Entities.Producto", "Producto")
                    .WithMany()
                    .HasForeignKey("ProductoId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_AjusteInventarioDetalles_Productos");

                b.HasOne("Solqaryn.Domain.Entities.ProductoVariante", "ProductoVariante")
                    .WithMany()
                    .HasForeignKey("ProductoVarianteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_AjusteInventarioDetalles_ProductoVariantes");

                b.Navigation("AjusteInventario");
                b.Navigation("Producto");
                b.Navigation("ProductoVariante");
            });
            // ERP-N1.4.D — contexto físico histórico de operaciones.
            modelBuilder.Entity("Solqaryn.Domain.Entities.CompraDetalle", b =>
            {
                b.Property<int?>("AlmacenId").HasColumnType("int");
                b.Property<int?>("UbicacionAlmacenId").HasColumnType("int");
                b.HasIndex("AlmacenId", "UbicacionAlmacenId")
                    .HasDatabaseName("IX_CompraDetalles_Almacen_Ubicacion");
                b.ToTable("CompraDetalles", null, t =>
                {
                    t.HasCheckConstraint("CK_CompraDetalles_Ubicacion_RequiereAlmacen", "`UbicacionAlmacenId` IS NULL OR `AlmacenId` IS NOT NULL");
                });
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.VentaDetalle", b =>
            {
                b.Property<int?>("AlmacenId").HasColumnType("int");
                b.Property<int?>("UbicacionAlmacenId").HasColumnType("int");
                b.HasIndex("AlmacenId", "UbicacionAlmacenId")
                    .HasDatabaseName("IX_VentaDetalles_Almacen_Ubicacion");
                b.ToTable("VentaDetalles", null, t =>
                {
                    t.HasCheckConstraint("CK_VentaDetalles_Ubicacion_RequiereAlmacen", "`UbicacionAlmacenId` IS NULL OR `AlmacenId` IS NOT NULL");
                });
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.ConsumoInsumoDetalle", b =>
            {
                b.Property<int?>("AlmacenId").HasColumnType("int");
                b.Property<int?>("UbicacionAlmacenId").HasColumnType("int");
                b.HasIndex("AlmacenId", "UbicacionAlmacenId")
                    .HasDatabaseName("IX_ConsumoInsumoDetalles_Almacen_Ubicacion");
                b.ToTable("ConsumoInsumoDetalles", null, t =>
                {
                    t.HasCheckConstraint("CK_ConsumoInsumoDetalles_Ubicacion_RequiereAlmacen", "`UbicacionAlmacenId` IS NULL OR `AlmacenId` IS NOT NULL");
                });
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.MovimientoInventario", b =>
            {
                b.Property<int?>("AlmacenId").HasColumnType("int");
                b.Property<int?>("UbicacionAlmacenId").HasColumnType("int");
                b.HasIndex("AlmacenId", "UbicacionAlmacenId")
                    .HasDatabaseName("IX_MovimientosInventario_Almacen_Ubicacion");

                // ERP-N1.5 — índices de trazabilidad declarados después de materializar
                // AlmacenId/UbicacionAlmacenId para mantener el snapshot determinista.
                b.HasIndex("ProductoId", "ProductoVarianteId", "Fecha")
                    .HasDatabaseName("IX_MovInv_Producto_Variante_Fecha_N15");
                b.HasIndex("AlmacenId", "UbicacionAlmacenId", "Fecha")
                    .HasDatabaseName("IX_MovInv_Almacen_Ubicacion_Fecha_N15");
                b.HasIndex("CompraId", "Fecha")
                    .HasDatabaseName("IX_MovInv_Compra_Fecha_N15");
                b.HasIndex("VentaId", "Fecha")
                    .HasDatabaseName("IX_MovInv_Venta_Fecha_N15");
                b.HasIndex("ConsumoInsumoId", "Fecha")
                    .HasDatabaseName("IX_MovInv_Consumo_Fecha_N15");
                b.HasIndex("AjusteInventarioId", "Fecha")
                    .HasDatabaseName("IX_MovInv_Ajuste_Fecha_N15");

                b.ToTable("MovimientosInventario", null, t =>
                {
                    t.HasCheckConstraint("CK_MovimientosInventario_Ubicacion_RequiereAlmacen", "`UbicacionAlmacenId` IS NULL OR `AlmacenId` IS NOT NULL");
                });
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.AjusteInventarioDetalle", b =>
            {
                b.Property<int?>("AlmacenId").HasColumnType("int");
                b.Property<int?>("UbicacionAlmacenId").HasColumnType("int");
                b.HasIndex("AlmacenId", "UbicacionAlmacenId")
                    .HasDatabaseName("IX_AjusteInventarioDetalles_Almacen_Ubicacion");
                b.ToTable("AjusteInventarioDetalles", null, t =>
                {
                    t.HasCheckConstraint("CK_AjusteInventarioDetalles_Ubicacion_RequiereAlmacen", "`UbicacionAlmacenId` IS NULL OR `AlmacenId` IS NOT NULL");
                });
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.CompraDetalle", b =>
            {
                b.HasOne("Solqaryn.Domain.Entities.Almacen", "Almacen")
                    .WithMany().HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_CompraDetalles_Almacenes_AlmacenId_N14");
                b.HasOne("Solqaryn.Domain.Entities.UbicacionAlmacen", "UbicacionAlmacen")
                    .WithMany().HasForeignKey("AlmacenId", "UbicacionAlmacenId")
                    .HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_CompraDetalles_Ubicacion_MismoAlmacen_N14");
                b.Navigation("Almacen");
                b.Navigation("UbicacionAlmacen");
            });
        }
    }
}
