// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Solqaryn.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart3(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity("Solqaryn.Domain.Entities.Almacen", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Activo")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true);

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("varchar(40)");

                b.Property<string>("CodigoActivoUnico")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasMaxLength(40)
                    .HasColumnType("varchar(40)")
                    .HasComputedColumnSql("IF(Eliminado = 0, UPPER(TRIM(Codigo)), NULL)", true);

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<bool>("Eliminado")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(false);

                b.Property<int?>("EliminadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("FechaEliminacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int>("SucursalId")
                    .HasColumnType("int");

                b.Property<int>("Tipo")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CodigoActivoUnico")
                    .IsUnique()
                    .HasDatabaseName("UX_Almacenes_Codigo_Activo");

                b.HasIndex("SucursalId")
                    .HasDatabaseName("IX_Almacenes_SucursalId");

                b.HasIndex("Tipo", "Activo", "Eliminado")
                    .HasDatabaseName("IX_Almacenes_Tipo_Estado");

                b.ToTable("Almacenes", (string)null);
            });
            modelBuilder.Entity("Solqaryn.Domain.Entities.UbicacionAlmacen", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Activa")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true);

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<int>("AlmacenId")
                    .HasColumnType("int");

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(60)
                    .HasColumnType("varchar(60)");

                b.Property<string>("CodigoActivoUnico")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasMaxLength(60)
                    .HasColumnType("varchar(60)")
                    .HasComputedColumnSql("IF(Eliminado = 0, UPPER(TRIM(Codigo)), NULL)", true);

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<bool>("Eliminado")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(false);

                b.Property<int?>("EliminadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("FechaEliminacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int>("Tipo")
                    .HasColumnType("int");

                b.Property<int?>("UbicacionPadreId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasAlternateKey("AlmacenId", "Id")
                    .HasName("AK_UbicacionesAlmacen_AlmacenId_Id");

                b.HasIndex("AlmacenId")
                    .HasDatabaseName("IX_UbicacionesAlmacen_AlmacenId");

                b.HasIndex("AlmacenId", "CodigoActivoUnico")
                    .IsUnique()
                    .HasDatabaseName("UX_UbicacionesAlmacen_Almacen_Codigo_Activo");

                b.HasIndex("AlmacenId", "UbicacionPadreId")
                    .HasDatabaseName("IX_UbicacionesAlmacen_Padre");

                b.HasIndex("Tipo", "Activa", "Eliminado")
                    .HasDatabaseName("IX_UbicacionesAlmacen_Tipo_Estado");

                b.ToTable("UbicacionesAlmacen", (string)null);
            });
        }
    }
}
