import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal, ChangeDetectionStrategy } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { finalize, forkJoin } from 'rxjs';
import { PermisosRuntimeService } from '../../../core/auth/permisos-runtime.service';
import {
  DevolucionProveedor,
  DevolucionProveedorCreateValue,
  DevolucionProveedorDetalle,
  DevolucionProveedorUpdateValue,
  EstadoDevolucionProveedor
} from '../../../core/models/devolucion-proveedor.model';
import { FacturaProveedor } from '../../../core/models/factura-proveedor.model';
import { RecepcionCompra, RecepcionCompraDetalle } from '../../../core/models/recepcion-compra.model';
import { DevolucionProveedorService } from '../../../services/devolucion-proveedor.service';
import { FacturaProveedorService } from '../../../services/factura-proveedor.service';
import { RecepcionCompraService } from '../../../services/recepcion-compra.service';

const UI = [CommonModule, RouterLink, MatButtonModule, MatCardModule, MatFormFieldModule, MatIconModule, MatInputModule, MatProgressSpinnerModule, MatSelectModule];

@Component({
  selector: 'app-devoluciones-proveedor-list',
  standalone: true,
  imports: UI,
  template: `
    <section class="page-shell" aria-labelledby="devoluciones-title">
      <header class="page-header"><div><p class="eyebrow">Compras empresariales</p><h1 id="devoluciones-title">Devoluciones a proveedor</h1><p>Consulta devoluciones, su estado y el crédito documental asociado.</p></div>@if (puedeCrear()) {<a mat-flat-button routerLink="/devoluciones-proveedor/nueva" data-testid="nueva-devolucion"><mat-icon>assignment_return</mat-icon> Nueva devolución</a>}</header>
      <mat-card><mat-card-content>
        <div class="filters">
          <mat-form-field appearance="outline"><mat-label>Estado</mat-label><mat-select [value]="estado" (selectionChange)="cambiarEstado($event.value)"><mat-option value="">Todos</mat-option><mat-option value="Borrador">Borrador</mat-option><mat-option value="Confirmada">Confirmada</mat-option><mat-option value="Anulada">Anulada</mat-option></mat-select></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>Proveedor ID</mat-label><input matInput type="number" min="1" [value]="proveedorId ?? ''" (input)="proveedorId = enteroOpcional($any($event.target).value)"></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>Orden ID</mat-label><input matInput type="number" min="1" [value]="ordenCompraId ?? ''" (input)="ordenCompraId = enteroOpcional($any($event.target).value)"></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>Recepción ID</mat-label><input matInput type="number" min="1" [value]="recepcionCompraId ?? ''" (input)="recepcionCompraId = enteroOpcional($any($event.target).value)"></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>Factura ID</mat-label><input matInput type="number" min="1" [value]="facturaProveedorId ?? ''" (input)="facturaProveedorId = enteroOpcional($any($event.target).value)"></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>Desde</mat-label><input matInput type="date" [value]="desdeUtc" (input)="desdeUtc = $any($event.target).value"></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>Hasta</mat-label><input matInput type="date" [value]="hastaUtc" (input)="hastaUtc = $any($event.target).value"></mat-form-field>
          <button mat-stroked-button type="button" (click)="aplicarFiltros()"><mat-icon>filter_alt</mat-icon> Aplicar</button>
        </div>
        @if (error()) {<div class="state-panel error" role="alert"><mat-icon>error_outline</mat-icon><span>{{ error() }}</span><button mat-button type="button" (click)="cargar()">Reintentar</button></div>} @else if (loading()) {<div class="state-panel" role="status"><mat-spinner diameter="36"></mat-spinner><span>Cargando devoluciones…</span></div>} @else {
          <div class="table-wrap"><table><thead><tr><th>Número</th><th>Proveedor</th><th>Orden</th><th>Recepción</th><th>Factura</th><th>Estado</th><th>Crédito</th><th><span class="sr-only">Acciones</span></th></tr></thead><tbody>
            @for (item of items(); track item.id) {<tr><td>{{ item.numeroDevolucion }}</td><td>{{ item.proveedorNombreSnapshot }}</td><td>#{{ item.ordenCompraId }}</td><td>#{{ item.recepcionCompraId }}</td><td>#{{ item.facturaProveedorId }}</td><td><span class="status" [class.confirmed]="esEstado(item.estado, 'Confirmada')" [class.cancelled]="esEstado(item.estado, 'Anulada')">{{ estadoNombre(item.estado) }}</span></td><td>{{ item.moneda }} {{ item.totalCredito | number:'1.2-2' }}</td><td><a mat-icon-button [routerLink]="['/devoluciones-proveedor', item.id]" [attr.aria-label]="'Ver devolución ' + item.numeroDevolucion"><mat-icon>visibility</mat-icon></a></td></tr>} @empty {<tr><td colspan="8" class="empty">No hay devoluciones para los filtros seleccionados.</td></tr>}
          </tbody></table></div>
          <footer class="pager"><span>{{ totalCount() }} registro(s)</span><div><button mat-button type="button" [disabled]="page <= 1" (click)="irPagina(page - 1)">Anterior</button><span>Página {{ page }}</span><button mat-button type="button" [disabled]="page * pageSize >= totalCount()" (click)="irPagina(page + 1)">Siguiente</button></div></footer>
        }
      </mat-card-content></mat-card>
    </section>
  `,
  changeDetection: ChangeDetectionStrategy.Eager,
  styles: [`.page-shell{display:grid;gap:1.25rem;max-width:1280px;margin:0 auto}.page-header{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem}.eyebrow{margin:0 0 .25rem;text-transform:uppercase;letter-spacing:.08em;font-size:.75rem;font-weight:700;opacity:.7}h1{margin:.1rem 0}.filters{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:.75rem;align-items:center}.state-panel{min-height:120px;display:flex;align-items:center;justify-content:center;gap:.75rem}.error{color:var(--mat-sys-error,#b3261e)}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:.8rem;text-align:left;border-bottom:1px solid rgba(127,127,127,.2);white-space:nowrap}.empty{text-align:center;padding:2rem}.status{display:inline-flex;padding:.2rem .55rem;border-radius:999px;background:rgba(127,127,127,.16)}.status.confirmed{background:rgba(46,125,50,.15)}.status.cancelled{background:rgba(183,28,28,.14)}.pager,.pager div{display:flex;justify-content:space-between;align-items:center;gap:.5rem}.pager{padding-top:1rem}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}@media(max-width:980px){.filters{grid-template-columns:repeat(2,minmax(140px,1fr))}}@media(max-width:680px){.page-header{flex-direction:column}.filters{grid-template-columns:1fr}.pager{align-items:flex-start;flex-direction:column}}`]
})
export class DevolucionesProveedorListComponent implements OnInit {
  private readonly service = inject(DevolucionProveedorService); private readonly permisos = inject(PermisosRuntimeService);
  readonly items = signal<DevolucionProveedor[]>([]); readonly loading = signal(false); readonly error = signal(''); readonly totalCount = signal(0); readonly puedeCrear = signal(false);
  page=1; pageSize=20; estado:''|'Borrador'|'Confirmada'|'Anulada'=''; proveedorId:number|null=null; ordenCompraId:number|null=null; recepcionCompraId:number|null=null; facturaProveedorId:number|null=null; desdeUtc=''; hastaUtc='';
  ngOnInit():void{this.puedeCrear.set(this.permisos.puede('Compras','Crear'));this.cargar();}
  cargar():void{this.loading.set(true);this.error.set('');this.service.getPaged({page:this.page,pageSize:this.pageSize,estado:this.estado||null,proveedorId:this.proveedorId,ordenCompraId:this.ordenCompraId,recepcionCompraId:this.recepcionCompraId,facturaProveedorId:this.facturaProveedorId,desdeUtc:this.inicioDia(this.desdeUtc),hastaUtc:this.finDia(this.hastaUtc)}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{this.items.set(r.data?.items??[]);this.totalCount.set(r.data?.totalCount??0);},error:()=>this.error.set('No fue posible cargar las devoluciones a proveedor.')});}
  aplicarFiltros():void{this.page=1;this.cargar();} cambiarEstado(v:''|'Borrador'|'Confirmada'|'Anulada'):void{this.estado=v;this.aplicarFiltros();} irPagina(v:number):void{this.page=Math.max(1,v);this.cargar();}
  enteroOpcional(v:string):number|null{const n=Number(v);return Number.isInteger(n)&&n>0?n:null;} estadoNombre(e:EstadoDevolucionProveedor):string{return e===1||e==='Borrador'?'Borrador':e===2||e==='Confirmada'?'Confirmada':e===3||e==='Anulada'?'Anulada':String(e);} esEstado(e:EstadoDevolucionProveedor,n:'Borrador'|'Confirmada'|'Anulada'):boolean{return this.estadoNombre(e)===n;}
  private inicioDia(v:string):string|null{return v?`${v}T00:00:00.000Z`:null;} private finDia(v:string):string|null{return v?`${v}T23:59:59.999Z`:null;}
}

@Component({
  selector:'app-devolucion-proveedor-form',standalone:true,imports:[...UI,ReactiveFormsModule],
  template:`<section class="page-shell" aria-labelledby="devolucion-form-title"><header class="page-header"><div><p class="eyebrow">Compras empresariales</p><h1 id="devolucion-form-title">{{esEdicion?'Editar devolución':'Nueva devolución a proveedor'}}</h1><p>La recepción debe estar recibida y la factura registrada. Solo se enviarán líneas con cantidad mayor que cero.</p></div><button mat-stroked-button type="button" (click)="volver()"><mat-icon>arrow_back</mat-icon> Volver</button></header>
  @if(loading()){<div class="state-panel" role="status"><mat-spinner diameter="36"></mat-spinner><span>Cargando información…</span></div>}@else{<form [formGroup]="form" (ngSubmit)="guardar()" class="form-grid" novalidate>
  @if(!esEdicion){<mat-form-field appearance="outline"><mat-label>Recepción recibida</mat-label><mat-select formControlName="recepcionCompraId" (selectionChange)="seleccionarRecepcion($event.value)" data-testid="recepcion-devolucion">@for(r of recepciones();track r.id){<mat-option [value]="r.id">{{r.numeroRecepcion}} — Orden #{{r.ordenCompraId}}</mat-option>}</mat-select>@if(form.controls.recepcionCompraId.touched&&form.controls.recepcionCompraId.invalid){<mat-error>Selecciona una recepción.</mat-error>}</mat-form-field><mat-form-field appearance="outline"><mat-label>Factura registrada</mat-label><mat-select formControlName="facturaProveedorId" data-testid="factura-devolucion">@for(f of facturasFiltradas();track f.id){<mat-option [value]="f.id">{{f.numeroFactura}} — {{f.proveedorNombreSnapshot}}</mat-option>}</mat-select>@if(form.controls.facturaProveedorId.touched&&form.controls.facturaProveedorId.invalid){<mat-error>Selecciona una factura de la misma orden.</mat-error>}</mat-form-field>}@else if(actual();as item){<div class="summary span-2"><span><strong>{{item.numeroDevolucion}}</strong> · {{item.proveedorNombreSnapshot}}</span><span>Recepción #{{item.recepcionCompraId}} · Factura #{{item.facturaProveedorId}}</span></div>}
  <mat-form-field appearance="outline" class="span-2"><mat-label>Motivo</mat-label><textarea matInput rows="3" formControlName="motivo" maxlength="500"></textarea>@if(form.controls.motivo.touched&&form.controls.motivo.invalid){<mat-error>El motivo es obligatorio y admite hasta 500 caracteres.</mat-error>}</mat-form-field><mat-form-field appearance="outline" class="span-2"><mat-label>Observaciones</mat-label><textarea matInput rows="2" formControlName="observaciones" maxlength="1000"></textarea></mat-form-field>
  @if(error()){<div class="state-panel error span-2" role="alert"><mat-icon>error_outline</mat-icon><span>{{error()}}</span></div>}
  @if(lineas().length){<div class="lines span-2" formArrayName="detalles">@for(linea of lineas();track linea.id;let i=$index){<article class="line-card" [formGroupName]="i"><div><strong>{{linea.productoSkuSnapshot||('Producto #'+linea.productoId)}}</strong><span>{{linea.productoNombreSnapshot||'Producto recibido'}}</span></div><div class="accepted"><small>Aceptada</small><strong>{{linea.cantidadAceptada}}</strong></div><mat-form-field appearance="outline"><mat-label>Cantidad a devolver</mat-label><input matInput type="number" min="0" [max]="linea.cantidadAceptada" step="0.0001" formControlName="cantidad" [attr.data-testid]="'cantidad-devolver-'+i">@if(detalle(i).controls['cantidad'].invalid&&detalle(i).controls['cantidad'].touched){<mat-error>Entre 0 y {{linea.cantidadAceptada}}.</mat-error>}</mat-form-field></article>}</div>}@else if(form.controls.recepcionCompraId.value){<div class="state-panel span-2">La recepción seleccionada no contiene líneas aceptadas devolvibles.</div>}
  <div class="actions span-2"><button mat-button type="button" (click)="volver()">Cancelar</button><button mat-flat-button type="submit" [disabled]="!puedeGuardar()" data-testid="guardar-devolucion">@if(saving()){<mat-spinner diameter="20" aria-label="Guardando devolución"></mat-spinner>}@else{<mat-icon>save</mat-icon>} {{esEdicion?'Guardar cambios':'Guardar borrador'}}</button></div></form>}</section>`,
  changeDetection: ChangeDetectionStrategy.Eager,
  styles:[`.page-shell{display:grid;gap:1.25rem;max-width:1120px;margin:0 auto}.page-header{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem}.eyebrow{margin:0 0 .25rem;text-transform:uppercase;letter-spacing:.08em;font-size:.75rem;font-weight:700;opacity:.7}h1{margin:.1rem 0}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.span-2{grid-column:1/-1}.state-panel{min-height:96px;display:flex;align-items:center;justify-content:center;gap:.75rem}.error{color:var(--mat-sys-error,#b3261e)}.summary{display:flex;justify-content:space-between;gap:1rem;padding:1rem;border-radius:12px;background:rgba(127,127,127,.08)}.lines{display:grid;gap:.75rem}.line-card{display:grid;grid-template-columns:minmax(220px,2fr) 110px minmax(190px,1fr);align-items:center;gap:1rem;padding:1rem;border:1px solid rgba(127,127,127,.2);border-radius:14px}.line-card>div:first-child,.accepted{display:grid;gap:.2rem}.line-card span{opacity:.72}.accepted{text-align:right}.actions{display:flex;justify-content:flex-end;gap:.75rem;align-items:center}@media(max-width:720px){.page-header{flex-direction:column}.form-grid,.line-card{grid-template-columns:1fr}.span-2{grid-column:1}.summary{flex-direction:column}.accepted{text-align:left}}`]
})
export class DevolucionProveedorFormComponent implements OnInit{
  private readonly fb=inject(FormBuilder);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly devoluciones=inject(DevolucionProveedorService);private readonly recepcionesService=inject(RecepcionCompraService);private readonly facturasService=inject(FacturaProveedorService);private readonly permisos=inject(PermisosRuntimeService);
  readonly recepciones=signal<RecepcionCompra[]>([]);readonly facturas=signal<FacturaProveedor[]>([]);readonly facturasFiltradas=signal<FacturaProveedor[]>([]);readonly lineas=signal<RecepcionCompraDetalle[]>([]);readonly actual=signal<DevolucionProveedor|null>(null);readonly loading=signal(false);readonly saving=signal(false);readonly error=signal('');esEdicion=false;devolucionId:number|null=null;
  readonly form=this.fb.group({recepcionCompraId:[null as number|null,Validators.required],facturaProveedorId:[null as number|null,Validators.required],motivo:['',[Validators.required,Validators.maxLength(500)]],observaciones:['',Validators.maxLength(1000)],detalles:this.fb.array([])});get detalles():FormArray{return this.form.controls.detalles;}
  ngOnInit():void{const id=Number(this.route.snapshot.paramMap.get('id'));this.esEdicion=Number.isInteger(id)&&id>0;this.devolucionId=this.esEdicion?id:null;this.loading.set(true);forkJoin({recepciones:this.recepcionesService.getPaged({page:1,pageSize:100,estado:'Recibida'}),facturas:this.facturasService.getPaged({page:1,pageSize:100,estado:'Registrada'})}).subscribe({next:({recepciones,facturas})=>{this.recepciones.set(recepciones.data?.items??[]);this.facturas.set(facturas.data?.items??[]);this.facturasFiltradas.set(this.facturas());if(this.esEdicion&&this.devolucionId)this.cargarEdicion(this.devolucionId);else this.loading.set(false);},error:()=>{this.loading.set(false);this.error.set('No fue posible cargar recepciones y facturas elegibles.');}});}
  seleccionarRecepcion(id:number|null):void{this.form.controls.facturaProveedorId.setValue(null);this.detalles.clear();this.lineas.set([]);if(!id){this.facturasFiltradas.set(this.facturas());return;}const r=this.recepciones().find(x=>x.id===id);this.facturasFiltradas.set(r?this.facturas().filter(x=>x.ordenCompraId===r.ordenCompraId):[]);this.cargarLineasRecepcion(id);}
  detalle(i:number):FormGroup{return this.detalles.at(i) as FormGroup;} puedeGuardar():boolean{const permiso=this.permisos.puede('Compras',this.esEdicion?'Editar':'Crear');return permiso&&!this.saving()&&!this.loading()&&this.form.controls.motivo.valid&&(this.esEdicion||(this.form.controls.recepcionCompraId.valid&&this.form.controls.facturaProveedorId.valid))&&this.detalles.controls.some(x=>Number(x.get('cantidad')?.value??0)>0)&&this.detalles.controls.every(x=>x.valid);}
  guardar():void{if(!this.puedeGuardar()){this.form.markAllAsTouched();this.error.set('Revisa los datos y registra al menos una cantidad a devolver.');return;}const detalles=this.detalles.controls.map(c=>c.getRawValue()).filter(v=>Number(v.cantidad)>0).map(v=>({recepcionCompraDetalleId:Number(v.recepcionCompraDetalleId),cantidad:Number(v.cantidad)}));const motivo=this.form.controls.motivo.value?.trim()||'';const observaciones=this.form.controls.observaciones.value?.trim()||null;this.saving.set(true);this.error.set('');if(this.esEdicion&&this.devolucionId){const payload:DevolucionProveedorUpdateValue={motivo,observaciones,detalles};this.devoluciones.update(this.devolucionId,payload).pipe(finalize(()=>this.saving.set(false))).subscribe({next:r=>void this.router.navigate(['/devoluciones-proveedor',r.data.id]),error:e=>this.error.set(this.mensajeError(e,'No fue posible actualizar la devolución.'))});return;}const payload:DevolucionProveedorCreateValue={recepcionCompraId:Number(this.form.controls.recepcionCompraId.value),facturaProveedorId:Number(this.form.controls.facturaProveedorId.value),motivo,observaciones,detalles};this.devoluciones.create(payload).pipe(finalize(()=>this.saving.set(false))).subscribe({next:r=>void this.router.navigate(['/devoluciones-proveedor',r.data.id]),error:e=>this.error.set(this.mensajeError(e,'No fue posible crear la devolución.'))});}
  volver():void{void this.router.navigate(['/devoluciones-proveedor']);}
  private cargarEdicion(id:number):void{this.devoluciones.getById(id).subscribe({next:r=>{const item=r.data;if(this.estadoNombre(item.estado)!=='Borrador'){void this.router.navigate(['/devoluciones-proveedor',item.id]);return;}this.actual.set(item);this.form.patchValue({recepcionCompraId:item.recepcionCompraId,facturaProveedorId:item.facturaProveedorId,motivo:item.motivo,observaciones:item.observaciones??''});const rec=this.recepciones().find(x=>x.id===item.recepcionCompraId);this.facturasFiltradas.set(this.facturas().filter(x=>!rec||x.ordenCompraId===rec.ordenCompraId));this.cargarLineasRecepcion(item.recepcionCompraId,item.detalles);},error:()=>{this.loading.set(false);this.error.set('No fue posible cargar la devolución.');}});}
  private cargarLineasRecepcion(id:number,existentes:DevolucionProveedorDetalle[]=[]):void{this.loading.set(true);this.recepcionesService.getById(id).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{const lineas=(r.data?.detalles??[]).filter(x=>x.cantidadAceptada>0);this.lineas.set(lineas);this.detalles.clear();for(const linea of lineas){const previa=existentes.find(x=>x.recepcionCompraDetalleId===linea.id);this.detalles.push(this.fb.group({recepcionCompraDetalleId:[linea.id,Validators.required],cantidad:[previa?.cantidad??0,[Validators.min(0),Validators.max(linea.cantidadAceptada)]]}));}},error:()=>this.error.set('No fue posible cargar las líneas de la recepción.')});}
  private estadoNombre(e:EstadoDevolucionProveedor):string{return e===1||e==='Borrador'?'Borrador':e===2||e==='Confirmada'?'Confirmada':e===3||e==='Anulada'?'Anulada':String(e);}private mensajeError(e:any,f:string):string{return e?.error?.detail||e?.error?.message||f;}
}

@Component({
  selector:'app-devolucion-proveedor-detail',standalone:true,imports:[...UI,ReactiveFormsModule],
  template:`<section class="page-shell" aria-labelledby="devolucion-detail-title">@if(loading()){<div class="state-panel" role="status"><mat-spinner diameter="36"></mat-spinner><span>Cargando devolución…</span></div>}@else if(error()){<div class="state-panel error" role="alert"><mat-icon>error_outline</mat-icon><span>{{error()}}</span><button mat-button type="button" (click)="cargar()">Reintentar</button></div>}@else if(item();as d){
  <header class="page-header"><div><p class="eyebrow">Compras empresariales</p><h1 id="devolucion-detail-title">{{d.numeroDevolucion}}</h1><p>{{d.proveedorNombreSnapshot}} · {{estadoNombre(d.estado)}}</p></div><div class="header-actions">@if(esEstado(d.estado,'Borrador')&&puedeEditar()){<a mat-stroked-button [routerLink]="['/devoluciones-proveedor',d.id,'editar']"><mat-icon>edit</mat-icon> Editar</a>}<a mat-button routerLink="/devoluciones-proveedor"><mat-icon>arrow_back</mat-icon> Volver</a></div></header>
  <div class="summary-grid"><mat-card><mat-card-content><small>Orden</small><strong>#{{d.ordenCompraId}}</strong></mat-card-content></mat-card><mat-card><mat-card-content><small>Recepción</small><strong>#{{d.recepcionCompraId}}</strong></mat-card-content></mat-card><mat-card><mat-card-content><small>Factura</small><strong>#{{d.facturaProveedorId}}</strong></mat-card-content></mat-card><mat-card><mat-card-content><small>Crédito total</small><strong>{{d.moneda}} {{d.totalCredito|number:'1.2-2'}}</strong></mat-card-content></mat-card></div>
  <mat-card><mat-card-content><h2>Documento</h2><dl><dt>Motivo</dt><dd>{{d.motivo}}</dd><dt>Observaciones</dt><dd>{{d.observaciones||'—'}}</dd><dt>Subtotal crédito</dt><dd>{{d.moneda}} {{d.subtotalCredito|number:'1.2-2'}}</dd><dt>Impuesto crédito</dt><dd>{{d.moneda}} {{d.impuestoCredito|number:'1.2-2'}}</dd></dl></mat-card-content></mat-card>
  <mat-card><mat-card-content><h2>Detalle</h2><div class="table-wrap"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Costo unitario</th><th>Impuesto unitario</th><th>Total crédito</th></tr></thead><tbody>@for(linea of d.detalles;track linea.id){<tr><td><strong>{{linea.productoSkuSnapshot||('#'+linea.productoId)}}</strong><br><span>{{linea.productoNombreSnapshot}}</span></td><td>{{linea.cantidad}}</td><td>{{d.moneda}} {{linea.costoUnitarioSnapshot|number:'1.2-4'}}</td><td>{{d.moneda}} {{linea.impuestoUnitarioSnapshot|number:'1.2-4'}}</td><td>{{d.moneda}} {{linea.totalCredito|number:'1.2-2'}}</td></tr>}</tbody></table></div></mat-card-content></mat-card>
  @if(esEstado(d.estado,'Borrador')&&puedeConfirmar()){<mat-card class="action-card"><mat-card-content><div><strong>Confirmar devolución</strong><p>La confirmación es una transición de negocio controlada por el servidor y no se puede editar después.</p></div><button mat-flat-button type="button" [disabled]="actionBusy()" (click)="confirmar()" data-testid="confirmar-devolucion"><mat-icon>check_circle</mat-icon> Confirmar</button></mat-card-content></mat-card>}
  @if(esEstado(d.estado,'Confirmada')&&puedeAnular()){<mat-card class="action-card"><mat-card-content><div><strong>Anular devolución</strong><p>Indica el motivo de anulación. El servidor valida la transición.</p></div><mat-form-field appearance="outline"><mat-label>Motivo de anulación</mat-label><input matInput maxlength="500" [value]="motivoAnulacion" (input)="motivoAnulacion=$any($event.target).value"></mat-form-field><button mat-stroked-button type="button" [disabled]="actionBusy()||!motivoAnulacion.trim()" (click)="anular()" data-testid="anular-devolucion"><mat-icon>cancel</mat-icon> Anular</button></mat-card-content></mat-card>}
  @if(d.fechaConfirmacionUtc){<p class="audit-note">Confirmada {{d.fechaConfirmacionUtc|date:'dd/MM/yyyy HH:mm'}} por {{d.confirmadaPorNombreSnapshot||('usuario #'+d.confirmadaPorUsuarioId)}}.</p>}@if(d.fechaAnulacionUtc){<p class="audit-note">Anulada {{d.fechaAnulacionUtc|date:'dd/MM/yyyy HH:mm'}} · {{d.motivoAnulacion}}</p>}
  }</section>`,
  changeDetection: ChangeDetectionStrategy.Eager,
  styles:[`.page-shell{display:grid;gap:1rem;max-width:1180px;margin:0 auto}.page-header,.header-actions,.action-card mat-card-content{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem}.eyebrow{margin:0 0 .25rem;text-transform:uppercase;letter-spacing:.08em;font-size:.75rem;font-weight:700;opacity:.7}h1{margin:.1rem 0}.summary-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem}.summary-grid mat-card-content{display:grid;gap:.3rem}.summary-grid small,.audit-note{opacity:.72}.summary-grid strong{font-size:1.1rem}dl{display:grid;grid-template-columns:170px 1fr;gap:.65rem 1rem}dt{font-weight:700}dd{margin:0}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:.75rem;text-align:left;border-bottom:1px solid rgba(127,127,127,.2)}td span{opacity:.72}.action-card mat-form-field{min-width:260px}.state-panel{min-height:120px;display:flex;align-items:center;justify-content:center;gap:.75rem}.error{color:var(--mat-sys-error,#b3261e)}@media(max-width:800px){.summary-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.page-header,.action-card mat-card-content{flex-direction:column}dl{grid-template-columns:1fr}.action-card mat-form-field{width:100%}}@media(max-width:520px){.summary-grid{grid-template-columns:1fr}}`]
})
export class DevolucionProveedorDetailComponent implements OnInit{
  private readonly route=inject(ActivatedRoute);private readonly service=inject(DevolucionProveedorService);private readonly permisos=inject(PermisosRuntimeService);readonly item=signal<DevolucionProveedor|null>(null);readonly loading=signal(false);readonly error=signal('');readonly actionBusy=signal(false);readonly puedeEditar=signal(false);readonly puedeConfirmar=signal(false);readonly puedeAnular=signal(false);motivoAnulacion='';
  ngOnInit():void{this.puedeEditar.set(this.permisos.puede('Compras','Editar'));this.puedeConfirmar.set(this.permisos.puede('Compras','Confirmar'));this.puedeAnular.set(this.permisos.puede('Compras','Anular'));this.cargar();}
  cargar():void{const id=Number(this.route.snapshot.paramMap.get('id'));if(!Number.isInteger(id)||id<=0){this.error.set('Identificador de devolución inválido.');return;}this.loading.set(true);this.error.set('');this.service.getById(id).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>this.item.set(r.data),error:()=>this.error.set('No fue posible cargar la devolución a proveedor.')});}
  confirmar():void{const d=this.item();if(!d||!this.esEstado(d.estado,'Borrador')||!this.puedeConfirmar())return;this.actionBusy.set(true);this.error.set('');this.service.confirmar(d.id).pipe(finalize(()=>this.actionBusy.set(false))).subscribe({next:r=>this.item.set(r.data),error:e=>this.error.set(this.mensajeError(e,'No fue posible confirmar la devolución.'))});}
  anular():void{const d=this.item(),motivo=this.motivoAnulacion.trim();if(!d||!motivo||!this.esEstado(d.estado,'Confirmada')||!this.puedeAnular())return;this.actionBusy.set(true);this.error.set('');this.service.anular(d.id,motivo).pipe(finalize(()=>this.actionBusy.set(false))).subscribe({next:r=>{this.item.set(r.data);this.motivoAnulacion='';},error:e=>this.error.set(this.mensajeError(e,'No fue posible anular la devolución.'))});}
  estadoNombre(e:EstadoDevolucionProveedor):string{return e===1||e==='Borrador'?'Borrador':e===2||e==='Confirmada'?'Confirmada':e===3||e==='Anulada'?'Anulada':String(e);}esEstado(e:EstadoDevolucionProveedor,n:'Borrador'|'Confirmada'|'Anulada'):boolean{return this.estadoNombre(e)===n;}private mensajeError(e:any,f:string):string{return e?.error?.detail||e?.error?.message||f;}
}
