namespace Solqaryn.Domain.Enums;

public enum ModuloSistema
{
    Dashboard = 1,
    Productos = 2,
    Categorias = 3,
    Compras = 4,
    Ventas = 5,
    Facturacion = 6,
    Finanzas = 7,
    Inventario = 8,
    Proveedores = 9,
    Clientes = 10,
    Usuarios = 11,
    Auditoria = 12,
    Configuracion = 13,
    Roles = 14,
    Permisos = 15,
    Descuentos = 16,
    Impuestos = 17,
    MovimientosInventario = 18,
    Colores = 19,
    Tallas = 20,
    Marcas = 21,
    Modelos = 22,
    CargasMasivas = 23,
    ReportesAdministrativos = 24,
    TiposClientes = 25,
    InsumosAdministrativos = 26,
    MetodosPago = 27,
    Sucursales = 28,
    Almacenes = 29,
    UbicacionesAlmacen = 30,
    Caja = 31
}
